services:
  ai-moderator:
    build: .
    image: findway-moderator:v4
    container_name: ai-moderator
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    deploy:
      resources:
        limits:
          memory: 3.5G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"