#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Automated Data Generator & Aggregator for CAUCASUS Cluster (v9, v9.1, v9.2)
Author: Maksym Nenashev (Systems Engineer)
"""

import sys
from pathlib import Path
import pandas as pd

BASE_DIR = Path(__file__).resolve().parent.parent
RAW_DIR = BASE_DIR / "raw"
PROCESSED_DIR = BASE_DIR / "data" / "processed"

DATASETS = {
    "v9_sexual": {
        "TR": """"text","label","language","country_group","source","confidence_hint","notes"
"Seni öldüreceğim seni aptal herif",1,"tr","CAUCASUS","curated","high","direct_threat"
"Nerede oturduğunu biliyorum kendine dikkat et",1,"tr","CAUCASUS","curated","high","stalking_threat"
"Bana çıplak fotoğraflarını gönderebilir misin",1,"tr","CAUCASUS","curated","high","explicit_request"
"Sen pis bir sürtük ve domuzsun",1,"tr","CAUCASUS","curated","high","overt_insult"
"Seni geberteceğim şerefsiz",1,"tr","CAUCASUS","curated","high","direct_threat"
"Para karşılığı cinsel hizmet sunuyor musun",1,"tr","CAUCASUS","curated","high","transactional_solicitation"
"Seni hemen şimdi çıplak görmek istiyorum",1,"tr","CAUCASUS","curated","high","explicit_request"
"Aileni bulup hepinize zarar vereceğim",1,"tr","CAUCASUS","curated","high","stalking_threat"
"Kes sesini seni lanet aptal",1,"tr","CAUCASUS","curated","high","overt_insult"
"Evinin önünde bekliyorum dışarı çık",1,"tr","CAUCASUS","curated","high","stalking_threat"
"Kemiklerini kıracağım senin",1,"tr","CAUCASUS","curated","high","direct_threat"
"Özel fotoğraflarını hemen gönder",1,"tr","CAUCASUS","curated","high","explicit_request"
"Hayatını tamamen mahvedeceğim",1,"tr","CAUCASUS","curated","high","direct_threat"
"Ağzına al seni lanet fahişe",1,"tr","CAUCASUS","curated","high","overt_insult"
"Doğduğuna pişman olacaksın",1,"tr","CAUCASUS","curated","high","direct_threat"
"Sokakta gördüğüm an öleceksin",1,"tr","CAUCASUS","curated","high","direct_threat"
"Çıplak fotoğraflarını ver yoksa yayarım",1,"tr","CAUCASUS","curated","high","explicit_request"
"Seni köpek gibi keseceğim",1,"tr","CAUCASUS","curated","high","direct_threat"
"Aşağılık pislik defol git buradan",1,"tr","CAUCASUS","curated","high","overt_insult"
"Hiçbir polis seni elimden kurtaramaz",1,"tr","CAUCASUS","curated","high","direct_threat"
"İyi durumda satılık ikinci el bisiklet",0,"tr","CAUCASUS","curated","high","neutral_listing"
"Hızlı yanıt ve mükemmel hizmet için teşekkürler",0,"tr","CAUCASUS","curated","high","neutral_communication"
"Yarın saat onda bir toplantı ayarlayabilir miyiz",0,"tr","CAUCASUS","curated","high","neutral_business"
"Ahşap yemek masası satın almak istiyorum",0,"tr","CAUCASUS","curated","high","neutral_listing"
"Merhaba hizmetiniz hakkında bir soru sormak istiyorum",0,"tr","CAUCASUS","curated","high","neutral_query"
"İstanbulda kiralık daire arıyorum",0,"tr","CAUCASUS","curated","high","neutral_listing"
"Faturayı e-posta adresime gönderebilir misiniz",0,"tr","CAUCASUS","curated","high","neutral_business"
"Kitap çok ilginç ve faydalıydı",0,"tr","CAUCASUS","curated","high","neutral_communication"
"Satılık çocuk kıyafetleri beden 92 sıfır",0,"tr","CAUCASUS","curated","high","neutral_listing"
"Müşteri hizmetlerinizin çalışma saatleri nedir",0,"tr","CAUCASUS","curated","high","neutral_query"
"Klinikte sağlık kontrolü için randevu sunuyoruz",0,"tr","CAUCASUS","curated","high","legit_services"
"Tiyatro için iki bilet sipariş etmek istiyorum",0,"tr","CAUCASUS","curated","high","neutral_business"
"Köpeğin her öğleden sonra yürüyüşe ihtiyacı var",0,"tr","CAUCASUS","curated","high","neutral_communication"
"Kurs önümüzdeki pazartesi saat dokuzda başlıyor",0,"tr","CAUCASUS","curated","high","neutral_business"
"Konferansta sizinle tanışmak bir zevkti",0,"tr","CAUCASUS","curated","high","neutral_communication"
"Yetkili oto servis tüm markaların tamirini yapar",0,"tr","CAUCASUS","curated","high","legit_services"
"Şehir merkezinde kiralık ofis alanları sunuyoruz",0,"tr","CAUCASUS","curated","high","legit_business"
"Haftada iki gün çocuklar için bakıcı arıyoruz",0,"tr","CAUCASUS","curated","high","legit_employment"
"Lise öğrencileri için matematik dersleri veriyoruz",0,"tr","CAUCASUS","curated","high","legit_services"
"Çok iyi durumda çalışma masası satılık",0,"tr","CAUCASUS","curated","high","neutral_listing"\n""",
        "GE": """"text","label","language","country_group","source","confidence_hint","notes"
"მოგკლავ შენი ნაგავი იდიოტო",1,"ka","CAUCASUS","curated","high","direct_threat"
"ვიცი სად ცხოვრობ ფრთხილად იყავი",1,"ka","CAUCASUS","curated","high","stalking_threat"
"შეგიძლია გამომიგზავნო შიშველი ფოტოები",1,"ka","CAUCASUS","curated","high","explicit_request"
"შენ ხარ ძუკნა და ღორი",1,"ka","CAUCASUS","curated","high","overt_insult"
"ცემით მოგკლავ ნაძირალა",1,"ka","CAUCASUS","curated","high","direct_threat"
"გთავაზობთ სექსუალურ მომსახურებას ფულის სანაცვლოდ",1,"ka","CAUCASUS","curated","high","transactional_solicitation"
"მინდა ახლავე გინახო შიშველი",1,"ka","CAUCASUS","curated","high","explicit_request"
"ვიპოვი შენს ოჯახს და დაგაზიანებთ",1,"ka","CAUCASUS","curated","high","stalking_threat"
"მოკეტე შენი საზიზღარი პირი",1,"ka","CAUCASUS","curated","high","overt_insult"
"სახლის წინ გელოდები გარეთ გამოდი",1,"ka","CAUCASUS","curated","high","stalking_threat"
"ძვლებს დაგიმტვრევ იცოდე",1,"ka","CAUCASUS","curated","high","direct_threat"
"გამოაგზავნე შენი პირადი ფოტოები ახლავე",1,"ka","CAUCASUS","curated","high","explicit_request"
"ცხოვრებას სრულიად დაგინგრობ",1,"ka","CAUCASUS","curated","high","direct_threat"
"მოწოვე შენი ნაგავი ბოზი",1,"ka","CAUCASUS","curated","high","overt_insult"
"ისანანებ რომ გაჩნდი ამ ქვეყანაზე",1,"ka","CAUCASUS","curated","high","direct_threat"
"ქუჩაში როგორც კი დაგინახავ მკვდარი ხარ",1,"ka","CAUCASUS","curated","high","direct_threat"
"მომეცი შიშველი ფოტოები თორემ გავავრცელებ",1,"ka","CAUCASUS","curated","high","explicit_request"
"ძაღლივით დაგკლავ იცოდე",1,"ka","CAUCASUS","curated","high","direct_threat"
"ნაგავო დაიკარგე აქედან ახლავე",1,"ka","CAUCASUS","curated","high","overt_insult"
"ვერცერთი პოლიციელი ვერ გადაგარჩენს ჩემგან",1,"ka","CAUCASUS","curated","high","direct_threat"
"იყიდება მეორადი ველოსიპედი კარგ მდგომარეობაში",0,"ka","CAUCASUS","curated","high","neutral_listing"
"გმადლობთ სწრაფი პასუხისთვის და კარგი მომსახურებისთვის",0,"ka","CAUCASUS","curated","high","neutral_communication"
"შეგვიძლია დავგეგმოთ შეხვედრა ხვალ ათ საათზე",0,"ka","CAUCASUS","curated","high","neutral_business"
"მინდა ვიყიდო ხის სასადილო მაგიდა",0,"ka","CAUCASUS","curated","high","neutral_listing"
"გამარჯობა მინდა დავსვა შეკითხვა თქვენს სერვისზე",0,"ka","CAUCASUS","curated","high","neutral_query"
"ვძებნი ბინას ქირით თბილისში",0,"ka","CAUCASUS","curated","high","neutral_listing"
"შეგიძლიათ გამოაგზავნოთ ინვოისი ჩემს ელფოსტაზე",0,"ka","CAUCASUS","curated","high","neutral_business"
"წიგნი იყო ძალიან საინტერესო და სასარგებლო",0,"ka","CAUCASUS","curated","high","neutral_communication"
"იყიდება ბავშვის ტანსაცმელი ზომა 92 ახალი",0,"ka","CAUCASUS","curated","high","neutral_listing"
"როგორია თქვენი მხარდაჭერის სამსახურის სამუშაო საათები",0,"ka","CAUCASUS","curated","high","neutral_query"
"გთავაზობთ ვიზიტს კლინიკაში ჯანმრთელობის შესამოწმებლად",0,"ka","CAUCASUS","curated","high","legit_services"
"მინდა შევუკვეთო ორი ბილეთი თეატრისთვის",0,"ka","CAUCASUS","curated","high","neutral_business"
"ძაღლს სჭირდება გასეირნება ყოველ დღე",0,"ka","CAUCASUS","curated","high","neutral_communication"
"კურსი იწყება მომავალ ორშაბათს ცხრა საათზე",0,"ka","CAUCASUS","curated","high","neutral_business"
"სასიამოვნო იყო თქვენი გაცნობა კონფერენციაზე",0,"ka","CAUCASUS","curated","high","neutral_communication"
"ავტორიზებული ავტოსერვისი ახორციელებს შეკეთებას",0,"ka","CAUCASUS","curated","high","legit_services"
"ქირავდება საოფისე ფართი ქალაქის ცენტრში",0,"ka","CAUCASUS","curated","high","legit_business"
"ვძებნით ძიძას ორი ბავშვისთვის კვირაში ორჯერ",0,"ka","CAUCASUS","curated","high","legit_employment"
"გთავაზობთ მათემატიკის გაკვეთილებს მოსწავლეებისთვის",0,"ka","CAUCASUS","curated","high","legit_services"
"იყიდება სამუშაო მაგიდა ძლიან კარგ მდგომარეობაში",0,"ka","CAUCASUS","curated","high","neutral_listing"\n""",
        "AM": """"text","label","language","country_group","source","confidence_hint","notes"
"Քեզ կսպանեմ անասուն իդիոտ",1,"hy","CAUCASUS","curated","high","direct_threat"
"Գիտեմ որտեղ ես ապրում զգույշ եղիր",1,"hy","CAUCASUS","curated","high","stalking_threat"
"Կարող ես ինձ մերկ նկարներ ուղարկել",1,"hy","CAUCASUS","curated","high","explicit_request"
"Դու պիղծ բոզ ես ու խոզ",1,"hy","CAUCASUS","curated","high","overt_insult"
"Քեզ կծեծեմ մինչև մահ",1,"hy","CAUCASUS","curated","high","direct_threat"
"Առաջարկում ես սեքսուալ ծառայություններ փողի դիմաց",1,"hy","CAUCASUS","curated","high","transactional_solicitation"
"Ուզում եմ քեզ մերկ տեսնել հիմա",1,"hy","CAUCASUS","curated","high","explicit_request"
"Կգտնեմ ընտանիքդ ու ձեզ վնաս կտամ",1,"hy","CAUCASUS","curated","high","stalking_threat"
"Ձայնդ կտրիր անպիտան իդիոտ",1,"hy","CAUCASUS","curated","high","overt_insult"
"Տանդ առաջ սպասում եմ դուրս արի",1,"hy","CAUCASUS","curated","high","stalking_threat"
"Ոսկորներդ կջարդեմ իմացիր",1,"hy","CAUCASUS","curated","high","direct_threat"
"Ուղարկիր անձնական նկարներդ հիմա",1,"hy","CAUCASUS","curated","high","explicit_request"
"Կյանքդ ամբողջությամբ կքանդեմ",1,"hy","CAUCASUS","curated","high","direct_threat"
"Ծծիր անպիտան բոզ",1,"hy","CAUCASUS","curated","high","overt_insult"
"Կզղջաս որ ծնվել ես այս աշխարհում",1,"hy","CAUCASUS","curated","high","direct_threat"
"Փողոցում տեսնեմ սպանված ես",1,"hy","CAUCASUS","curated","high","direct_threat"
"Տուր մերկ նկարներդ թե չէ կտարածեմ",1,"hy","CAUCASUS","curated","high","explicit_request"
"Շան պես կմորթեմ քեզ",1,"hy","CAUCASUS","curated","high","direct_threat"
"Աղբ ռադ եղիր այստեղից",1,"hy","CAUCASUS","curated","high","overt_insult"
"Ոչ մի ոստիկան քեզ իմ ձեռքից չի փրկի",1,"hy","CAUCASUS","curated","high","direct_threat"
"Վաճառվում է օգտագործված հեծանիվ լավ վիճակում",0,"hy","CAUCASUS","curated","high","neutral_listing"
"Շնորհակալություն արագ պատասխանի և լավ ծառայության համար",0,"hy","CAUCASUS","curated","high","neutral_communication"
"Կարող ենք հանդիպում նշանակել վաղը ժամը տասին",0,"hy","CAUCASUS","curated","high","neutral_business"
"Ուզում եմ գնել փայտե ճաշասեղան",0,"hy","CAUCASUS","curated","high","neutral_listing"
"Բարև ձեզ ուզում եմ հարց տալ ձեր ծառայության մասին",0,"hy","CAUCASUS","curated","high","neutral_query"
"Փնտրում եմ վարձով բնակարան Երևանում",0,"hy","CAUCASUS","curated","high","neutral_listing"
"Կարող եք հաշիվն ուղարկել իմ էլեկտրոնային փոստին",0,"hy","CAUCASUS","curated","high","neutral_business"
"Գիրքը շատ հետաքրքիր էր և օգտակար",0,"hy","CAUCASUS","curated","high","neutral_communication"
"Վաճառվում են մանկական հագուստ 92 չափսի նոր",0,"hy","CAUCASUS","curated","high","neutral_listing"
"Որոնք են ձեր աջակցման ծառայության աշխատանքային ժամերը",0,"hy","CAUCASUS","curated","high","neutral_query"
"Առաջարկում ենք այցելություն կլինիկա առողջությունը ստուգելու համար",0,"hy","CAUCASUS","curated","high","legit_services"
"Կուզենայի պատվիրել երկու տոմս թատրոնի համար",0,"hy","CAUCASUS","curated","high","neutral_business"
"Շունը զբոսանքի կարիք ունի ամեն օր",0,"hy","CAUCASUS","curated","high","neutral_communication"
"Դասընթացը սկսվում է հաջորդ երկուշաբթի ժամը իննին",0,"hy","CAUCASUS","curated","high","neutral_business"
"Հաճելի էր ծանոթանալ ձեզ հետ համաժողովում",0,"hy","CAUCASUS","curated","high","neutral_communication"
"Ավտոսպասարկման կենտրոնը կատարում է վերանորոգում",0,"hy","CAUCASUS","curated","high","legit_services"
"Վարձով ենք տալիս տարածք քաղաքի կենտրոնում",0,"hy","CAUCASUS","curated","high","legit_business"
"Փնտրում ենք դայակ երկու երեխայի համար շաբաթը երկու օր",0,"hy","CAUCASUS","curated","high","legit_employment"
"Առաջարկում ենք մաթեմատիկայի դասընթացներ աշակերտների համար",0,"hy","CAUCASUS","curated","high","legit_services"
"Վաճառվում է գրասեղան շատ լավ վիճակում",0,"hy","CAUCASUS","curated","high","neutral_listing"\n""",
        "AZ": """"text","label","language","country_group","source","confidence_hint","notes"
"Səni öldürəcəyəm səni axmaq idiot",1,"az","CAUCASUS","curated","high","direct_threat"
"Harada yaşadığını bilirəm özündən muğayat ol",1,"az","CAUCASUS","curated","high","stalking_threat"
"Mənə çılpaq şəkillərini göndərə bilərsən",1,"az","CAUCASUS","curated","high","explicit_request"
"Sən qəhbə və donuzsan",1,"az","CAUCASUS","curated","high","overt_insult"
"Səni döyüb gəbərdəcəyəm şərəfsiz",1,"az","CAUCASUS","curated","high","direct_threat"
"Pul müqabilində cinsi xidmət təklif edirsən",1,"az","CAUCASUS","curated","high","transactional_solicitation"
"Səni indi çılpaq görmək istəyirəm",1,"az","CAUCASUS","curated","high","explicit_request"
"Ailəni tapıb hamınıza xətər yetirəcəyəm",1,"az","CAUCASUS","curated","high","stalking_threat"
"Kəs səsini səni lənətə gəlmiş idiot",1,"az","CAUCASUS","curated","high","overt_insult"
"Evinin qabağında gözləyirəm çölə çıx",1,"az","CAUCASUS","curated","high","stalking_threat"
"Sümüklerini sındıracağam sənin",1,"az","CAUCASUS","curated","high","direct_threat"
"Şəxsi şəkillərini dərhal göndər",1,"az","CAUCASUS","curated","high","explicit_request"
"Həyatını tamamilə məhv edəcəyəm",1,"az","CAUCASUS","curated","high","direct_threat"
"Ağzına al səni lənətə gəlmiş fahişə",1,"az","CAUCASUS","curated","high","overt_insult"
"Doğulduğuna peşman olacaqsan",1,"az","CAUCASUS","curated","high","direct_threat"
"Küçədə gördüyüm an öləcəksən",1,"az","CAUCASUS","curated","high","direct_threat"
"Çılpaq şəkillərini ver yoxsa yayacağam",1,"az","CAUCASUS","curated","high","explicit_request"
"Səni it kimi kəsəcəyəm",1,"az","CAUCASUS","curated","high","direct_threat"
"Zibil parçası rədd ol buradan",1,"az","CAUCASUS","curated","high","overt_insult"
"Heç bir polis səni əlimdən xilas edə bilməz",1,"az","CAUCASUS","curated","high","direct_threat"
"Yaxşı vəziyyətdə işlənmiş velosiped satılır",0,"az","CAUCASUS","curated","high","neutral_listing"
"Tez cavab və əla xidmət üçün təşəkkürlər",0,"az","CAUCASUS","curated","high","neutral_communication"
"Sabah saat onda görüş təyin edə bilərikmi",0,"az","CAUCASUS","curated","high","neutral_business"
"Taxta yemək masası almaq istəyirəm",0,"az","CAUCASUS","curated","high","neutral_listing"
"Salam xidmətiniz haqqında sual vermək istəyirəm",0,"az","CAUCASUS","curated","high","neutral_query"
"Bakıda kirayə mənzil axtarıram",0,"az","CAUCASUS","curated","high","neutral_listing"
"Hesabı e-poçt ünvanıma göndərə bilərsinizmi",0,"az","CAUCASUS","curated","high","neutral_business"
"Kitab çox maraqlı və faydalı idi",0,"az","CAUCASUS","curated","high","neutral_communication"
"Satılır uşaq geyimləri ölçü 92 təzə",0,"az","CAUCASUS","curated","high","neutral_listing"
"Müştəri xidmətinizin iş saatları nə vaxtdır",0,"az","CAUCASUS","curated","high","neutral_query"
"Klinikada sağlamlıq yoxlanışı üçün qəbul təklif edirik",0,"az","CAUCASUS","curated","high","legit_services"
"Teatr üçün iki bilet sifariş etmək istəyirəm",0,"az","CAUCASUS","curated","high","neutral_business"
"İtin hər gün günortadan sonra gəzməyə ehtiyacı var",0,"az","CAUCASUS","curated","high","neutral_communication"
"Kurs gələn bazar ertəsi saat doqquzda başlayır",0,"az","CAUCASUS","curated","high","neutral_business"
"Konfransda sizinlə tanış olmaq xoş idi",0,"az","CAUCASUS","curated","high","neutral_communication"
"Rəsmi avtoservis bütün markaların təmirini edir",0,"az","CAUCASUS","curated","high","legit_services"
"Şəhər mərkəzində icarəyə ofis sahələri təklif edirik",0,"az","CAUCASUS","curated","high","legit_business"
"Həftədə iki gün uşaqlar üçün dayə axtarırıq",0,"az","CAUCASUS","curated","high","legit_employment"
"Məktəblilər üçün riyaziyyat dərsləri veririk",0,"az","CAUCASUS","curated","high","legit_services"
"Çox yaxşı vəziyyətdə yazı masası satılır",0,"az","CAUCASUS","curated","high","neutral_listing"\n""",
    },
    "v9.1_sexual": {
        "TR": """"text","label","language","country_group","source","confidence_hint","notes"
"a_p_t_a_l_h_e_r_i_f",1,"tr","CAUCASUS","curated","high","obfuscation_spaces"
"o.l.d.u.r.e.c.e.g.i.m",1,"tr","CAUCASUS","curated","high","obfuscation_dots"
"c1lp4k f0t0gr4fl4r",1,"tr","CAUCASUS","curated","high","leet_speak"
"s_u_r_t_u_k_p_i_s_l_i_k",1,"tr","CAUCASUS","curated","high","obfuscation_spaces"
"g.e.b.e.r.t.e.c.e.g.i.m",1,"tr","CAUCASUS","curated","high","obfuscation_dots"
"f_a_h_i_s_e_l_a_n_e_t",1,"tr","CAUCASUS","curated","high","obfuscation_spaces"
"m.a.h.v.e.d.e.c.e.g.i.m",1,"tr","CAUCASUS","curated","high","obfuscation_dots"
"f0t0_c!lp4k",1,"tr","CAUCASUS","curated","high","leet_speak"
"k.e.s.e.c.e.g.i.m_k.o.p.e.k",1,"tr","CAUCASUS","curated","high","obfuscation_dots"
"a_s_a_g_i_l_i_k_p_i_s_l_i_k",1,"tr","CAUCASUS","curated","high","obfuscation_spaces"
"c_i_l_p_a_k_p_i me_c_s",1,"tr","CAUCASUS","curated","high","obfuscation_spaces"
"k.e.m.i.k.l.e.r.i.n.i_k.i.r.a.c.a.g.i.m",1,"tr","CAUCASUS","curated","high","obfuscation_dots"
"a_g_z_i_n_a_a_l",1,"tr","CAUCASUS","curated","high","obfuscation_spaces"
"o_l_e_c_e_k_s_i_n_s_o_k_a_k_t_a",1,"tr","CAUCASUS","curated","high","obfuscation_spaces"
"s_u_r_t_u_k_d_o_m_u_z",1,"tr","CAUCASUS","curated","high","obfuscation_spaces"
"o_l_d_u_r_e_c_e_g_i_m_b_u_g_u_n",1,"tr","CAUCASUS","curated","high","obfuscation_spaces"
"f!h!s3_u_b_i_j_e_m",1,"tr","CAUCASUS","curated","high","leet_speak"
"f_a_h_i_s_e_k_u_r_v_a",1,"tr","CAUCASUS","curated","high","obfuscation_spaces"
"c.i.l.p.a.k_f.o.t.o_y.e.n.i",1,"tr","CAUCASUS","curated","high","obfuscation_dots"
"k_e_s me_k_o_p_e_k",1,"tr","CAUCASUS","curated","high","obfuscation_spaces"
"S.a.t.i.l.i.k_b.i.s.i.k.l.e.t",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"T.e.s.e.k.k.u.r.l.e.r_h.i.z.m.e.t",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"T.o.p.l.a.n.t.i_y.a.r.i.n",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"M.a.s.a_s.a.t.i me.n.a.l.m.a.k",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"F.a.t.u.r.a_e.p.o.s.t.a",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"K.i.t.a.p_f.a.y.d.a.l.i",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"C.o.c.u.k_k.i.y.a.f.e.t.i",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"C.a.l.i.s.m.a_s.a.a.t.l.a.r.i",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"R.a.n.d.e.v.u_k.l.i.n.i.k",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"B.i.l.e.t_t.i.y.a.t.r.o",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"O.t.o_s.e.r.v.i.s_t.a.m.i.r",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"O.f.i.s_k.i.r.a.l.i.k",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"C.o.c.u.k_b.a.k.i.c.i.s.i",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"M.a.t.e.m.a.t.i.k_d.e.r.s.i",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"C.a.l.i.s.m.a_m.a.s.a.s.i",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"D.a.i.r.e_k.i.r.a.l.i.k",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"A.r.a.b.a_a.l.i.m.i",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"C.e.v.i.r.i_h.i.z.m.e.t.i",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"M.u.k.e.m.m.e.l_u.r.u.n",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"
"S.i.p.a.r.i.s_t.e.s.l.i.m.a.t",0,"tr","CAUCASUS","curated","high","neutral_obfuscated"\n""",
        "GE": """"text","label","language","country_group","source","confidence_hint","notes"
"მ_ო_გ_კ_ლ_ა_ვ_ი_დ_ი_ო_ტ_ო",1,"ka","CAUCASUS","curated","high","obfuscation_spaces"
"შ.ი.შ.ვ.ე.ლ.ი_ფ.ო.ტ.ო.ე.ბ.ი",1,"ka","CAUCASUS","curated","high","obfuscation_dots"
"ც_ე_მ_ი_თ_მ_ო_გ_კ_ლ_ა_ვ",1,"ka","CAUCASUS","curated","high","obfuscation_spaces"
"ძ_უ_კ_ნ_ა_ნ_ა_ძ_ი_რ_ა_ლ_ა",1,"ka","CAUCASUS","curated","high","obfuscation_spaces"
"დ.ა.გ.ი.ნ.გ.რ.ე.ვ_ცხოვრებას",1,"ka","CAUCASUS","curated","high","obfuscation_dots"
"ბ_ო_ზ_ი_ნ_ა_გ_ა_ვ_ი",1,"ka","CAUCASUS","curated","high","obfuscation_spaces"
"დ.ა.გ.კ.ლ.ა.ვ_ძ.ა.ღ.ლ.ი.ვ.ი.თ",1,"ka","CAUCASUS","curated","high","obfuscation_dots"
"ნ!გ4ვ0_ს4ზ!ზღ4რ!,",1,"ka","CAUCASUS","curated","high","leet_speak"
"დ.ა.გ.ი me.ტ.ვ.რ.ე.ვ_ძ.ვ.ლ.ე.ბ.ს",1,"ka","CAUCASUS","curated","high","obfuscation_dots"
"ნ_ა_გ_ა_ვ_ო_დ_ა_ი_კ_ა_რ_გ_ე",1,"ka","CAUCASUS","curated","high","obfuscation_spaces"
"შ_ი_შ_ვ_ე_ლ_ი_ფ_ო_ტ_ო_ე_ბ_ი_ნ_უ",1,"ka","CAUCASUS","curated","high","obfuscation_spaces"
"მოგკლავ_ნაძირალა_დღეს",1,"ka","CAUCASUS","curated","high","obfuscation_spaces"
"მ_ო_წ_ო_ვ_ე_ნ_ა_გ_ა_ვ_ო",1,"ka","CAUCASUS","curated","high","obfuscation_spaces"
"მ_კ_ვ_დ_ა_რ_ი_ხ_ა_რ",1,"ka","CAUCASUS","curated","high","obfuscation_spaces"
"ღ_ო_რ_ი_ძ_უ_კ_ნ_ა",1,"ka","CAUCASUS","curated","high","obfuscation_spaces"
"მ_ო_გ_კ_ლ_ა_ვ_დ_ღ_ე_ს",1,"ka","CAUCASUS","curated","high","obfuscation_spaces"
"ბ0ზ!_მ_ო_გ_კ_ლ_ა_ვ",1,"ka","CAUCASUS","curated","high","leet_speak"
"ბ_ო_ზ_ი_მ_ო_გ_კ_ლ_ა_ვ",1,"ka","CAUCASUS","curated","high","obfuscation_spaces"
"შ.ი.შ.ვ.ე.ლ.ი_ს.უ.რ.ა.თ.ე.ბ.ი",1,"ka","CAUCASUS","curated","high","obfuscation_dots"
"დ.ა.გ.კ.ლ.ა.ვ_ნ.ა.გ.ა.ვ.ო",1,"ka","CAUCASUS","curated","high","obfuscation_dots"
"ი.ყ.ი.დ.ე.ბ.ა_ვ.ე.ლ.ო.ს.ი.პ.ე.დ.ი",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"გ.მ.ა.დ.ლ.ო.ბ.თ_მ.ო.მ.ს.ა.ხ.უ.რ.ე.ბ.ი.ს.თ.ვ.ი.ს",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"შ.ე.ხ.ვ.ე.დ.რ.ა_ხ.ვ.ა.ლ",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"მ.ა.გ.ი.დ.ა_ი.ყ.ი.დ.ე.ბ.ა",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"ინვოისი_ელფოსტაზე",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"წ.ი.გ.ნ.ი_ს.ა.ი.ნ.თ.ე.რ.ე.ს.ო",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"ბ.ა.ვ.შ.ვ.ი.ს_ტ.ა.ნ.ს.ა.ც.მ.ე.ლ.ი",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"ს.ა.მ.უ.შ.ა.ო_ს.ა.ა.თ.ე.ბ.ი",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"ვ.ი.ზ.ი.ტ.ი_კ.ლ.ი.ნ.ი.კ.ა.შ.ი",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"ბ.ი.ლ.ე.თ.ე.ბ.ი_თ.ე.ა.ტ.რ.შ.ი",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"ა.ვ.ტ.ო.ს.ე.რ.ვ.ი.ს.ი_შ.ე me.კ.ე.თ.ე.ბ.ა",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"ო.ფ.ი.ს.ი_ქ.ი.რ.ი.თ",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"ძ.ი.ძ.ა_ბ.ა.ვ.შ.ვ.ე.ბ.ი.ს.თ.ვ.ი.ს",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"მ.ა.თ.ე.მ.ა.ტ.ი.კ.ა_გ.ა.კ.ვ.ე.თ.ი.ლ.ე.ბ.ი",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"ს.ა.მ.უ.შ.ა.ო_მ.ა.გ.ი.დ.ა",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"ბ.ი.ნ.ა_ქ.ი.რ.ი.თ_თ.ბ.ი.ლ.ი.ს.შ.ი",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"ა.ვ.ტ.ო.მ.ო.ბ.ი.ლ.ი.ს_ყ.ი.დ.ვ.ა",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"თ.ა.რ.გ.მ.ნ.ა_ს.ე.რ.ვ.ი.ს.ი",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"ჩ.ა.ნ.თ.ა_ი.ყ.ი.დ.ე.ბ.ა",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"
"შ.ე me.კ.ვ.ე.თ.ი.ს_მ.ი.წ.ო.დ.ე.ბ.ა",0,"ka","CAUCASUS","curated","high","neutral_obfuscated"\n""",
        "AM": """"text","label","language","country_group","source","confidence_hint","notes"
"կ_ս_պ_ա_ն_ե_մ_ի_դ_ի_ո_տ",1,"hy","CAUCASUS","curated","high","obfuscation_spaces"
"մ.ե.ր.կ_ն.կ.ա.ր.ն.ե.ր",1,"hy","CAUCASUS","curated","high","obfuscation_dots"
"կ_ծ_ե_ծ_ե_մ_մ_ի_ն_չ_և_մ_ա_հ",1,"hy","CAUCASUS","curated","high","obfuscation_spaces"
"բ_ո_զ_ա_ն_ա_ս_ո_ւ_ն",1,"hy","CAUCASUS","curated","high","obfuscation_spaces"
"կ.ք.ա.ն.դ.ե.մ_կ.յ.ա.ն.ք.դ",1,"hy","CAUCASUS","curated","high","obfuscation_dots"
"ծ_ծ_ի_ր_ա_ն_պ_ի_տ_ա_ն",1,"hy","CAUCASUS","curated","high","obfuscation_spaces"
"կ.մ.ո.ր.թ.ե.մ_շ.ա.ն_պ.ե.ս",1,"hy","CAUCASUS","curated","high","obfuscation_dots"
"ա3ղբ_ռ4դ_ե3ղ!ր",1,"hy","CAUCASUS","curated","high","leet_speak"
"կ.ջ.ա.ր.դ.ե.մ_ո.ս.կ.ո.ր.ն.ե.ր.դ",1,"hy","CAUCASUS","curated","high","obfuscation_dots"
"ա_ղ_բ_ռ_ա_դ_ե_ղ_ի_ր",1,"hy","CAUCASUS","curated","high","obfuscation_spaces"
"մ_ե_ր_կ_ն_կ_ա_ր_ն_ե_ր_տ_ո_ւ_ր",1,"hy","CAUCASUS","curated","high","obfuscation_spaces"
"սպանված_ես_այսօր",1,"hy","CAUCASUS","curated","high","obfuscation_spaces"
"ծ_ծ_ի_ր_բ_ո_զ",1,"hy","CAUCASUS","curated","high","obfuscation_spaces"
"ս_պ_ա_ն_վ_ա_ծ_ե_ս",1,"hy","CAUCASUS","curated","high","obfuscation_spaces"
"խ_ո_զ_բ_ո_զ",1,"hy","CAUCASUS","curated","high","obfuscation_spaces"
"կ_ս_պ_ա_ն_ե_մ_ք_ե_զ",1,"hy","CAUCASUS","curated","high","obfuscation_spaces"
"բ0զ!_ս_պ_ա_ն_ո_ւ_մ",1,"hy","CAUCASUS","curated","high","leet_speak"
"բ_ո_զ_ս_պ_ա_ն_ո_ւ_մ",1,"hy","CAUCASUS","curated","high","obfuscation_spaces"
"մ.ե.ր.կ_լ.ո.ւ.ս.ա.ն.կ.ա.ր.ն.ե.ր",1,"hy","CAUCASUS","curated","high","obfuscation_dots"
"կ.մ.ո.ր.թ.ե.մ_ա_ղ_բ",1,"hy","CAUCASUS","curated","high","obfuscation_dots"
"Վ.ա.ճ.ա.ռ.վ.ո.ւ.մ_է_հ.ե.ծ.ա.ն.ի.վ",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Շ.ն.ո.ր.հ.ա.կ.ա.լ.ո.ւ.թ.յ.ո.ւ.ն_ծ.ա.ռ.ա.յ.ո.ւ.թ.յ.ա.ն_հ.ա.մ.ա.ր",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Հ.ա.ն.դ.ի.պ.ո.ւ.մ_վ.ա.ղ.ը",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Ս.ե.ղ.ա.ն_վ.ա.ճ.ա.ռ.ք",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Հ.ա.շ.ի.վ_է.լ.փ.ո.ս.տ.ի.ն",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Գ.ի.ր.ք_հ.ե.տ.ա.ք.ր.ք.ի.ր",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Մ.ա.ն.կ.ա.կ.ա.ն_հ.ա.գ.ո.ւ.ս.տ",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Ա.շ.խ.ա.տ.ա.ն.ք.ա.յ.ի.ն_ժ.ա.մ.ե.ր",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Ա.յ.ց_կ.լ.ի.ն.ի.կ.ա",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Տ.ո.մ.ս.ե.ր_թ.ա.տ.ր.ո.ն",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Ա.վ.տ.ո.ս.պ.ա.ս.ա.ր.կ.ո.ւ.մ",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Տ.ա.ր.ա.ծ.ք_վ.ա.ր.ձ.ո.վ",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Դ.ա.յ.ա.կ_ե.ր.ե.խ.ա.ն.ե.ր.ի_հ.ա.մ.ա.ր",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Մ.ա.թ.ե.մ.ա.տ.ի.կ.ա_դ.ա.ս.ե.ր",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Գ.ր.ա.ս.ե.ղ.ա.ն_վ.ա.ճ.ա.ռ.ք",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Բ.ն.ա.կ.ա.ր.ա.ն_Ե.ր.և.ա.ն.ո.ւ.մ",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Ա.վ.տ.ո me.ք.ե.ն.ա_գ.ն.ո.ւ.մ",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Թ.ա.ր.գ.մ.ա.ն.ո.ւ.թ.յ.ո.ւ.ն",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Ա.պ.ր.ա.ն.ք_լ.ա.վ",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"
"Ա.ռ.ա.ք.ո.ւ.մ_արագ",0,"hy","CAUCASUS","curated","high","neutral_obfuscated"\n""",
        "AZ": """"text","label","language","country_group","source","confidence_hint","notes"
"a_x_m_a_q_i_d_i_o_t",1,"az","CAUCASUS","curated","high","obfuscation_spaces"
"o.l.d.u.r.e.c.e.y.e.m",1,"az","CAUCASUS","curated","high","obfuscation_dots"
"c1lp4q s3k!ll3r",1,"az","CAUCASUS","curated","high","leet_speak"
"q_e_h_b_e_d_o_n_u_z",1,"az","CAUCASUS","curated","high","obfuscation_spaces"
"g.e.b.e.r.d.e.c.e.y.e.m",1,"az","CAUCASUS","curated","high","obfuscation_dots"
"f_a_h_i_s_e_l_e_n_e_t",1,"az","CAUCASUS","curated","high","obfuscation_spaces"
"m.e me.h.v_e.d.e.c.e.y.e.m",1,"az","CAUCASUS","curated","high","obfuscation_dots"
"s3k!l_c!lp4q",1,"az","CAUCASUS","curated","high","leet_speak"
"k.e.s.e.c.e.y.e.m_i.t",1,"az","CAUCASUS","curated","high","obfuscation_dots"
"z_i_b_i_l_p_a_r_c_a_s_i",1,"az","CAUCASUS","curated","high","obfuscation_spaces"
"c_i_l_p_a_q_s_e me_k_i_l_l_e_r",1,"az","CAUCASUS","curated","high","obfuscation_spaces"
"s.u.m.u me.k.l.e.r.i.n.i_s.i.n.d.i.r.a.c.a.g.a.m",1,"az","CAUCASUS","curated","high","obfuscation_dots"
"a_g_z_i_n_a_a_l",1,"az","CAUCASUS","curated","high","obfuscation_spaces"
"o_l me.c me.k_s_e_n_k_u_c me_a_d_a",1,"az","CAUCASUS","curated","high","obfuscation_spaces"
"q_e_h_b_e_s_v_i_n",1,"az","CAUCASUS","curated","high","obfuscation_spaces"
"o_l_d_u_r_e_c_e_y_e_m_b me_u_g me_u_n",1,"az","CAUCASUS","curated","high","obfuscation_spaces"
"f!h!s3_u_b_i_j_e_m",1,"az","CAUCASUS","curated","high","leet_speak"
"f_a_h_i_s_e_q_e_h_b_e",1,"az","CAUCASUS","curated","high","obfuscation_spaces"
"c.i.l.p.a.q_s.e me.k.i.l_y.e.n.i",1,"az","CAUCASUS","curated","high","obfuscation_dots"
"k_e_s me_i_t",1,"az","CAUCASUS","curated","high","obfuscation_spaces"
"S.a.t.i.l.i.r_v.e.l.o.s.i.p.e.d",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"T.e.s.e me.k.k.u.r.l.e.r_x.i.d me.m.e.t",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"G.o.r.u.s_s.a.b.a.h",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"M.a.s.a_a.l.m.a.q",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"H.e.s.a.b_e.p.o.c.t",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"K.i.t.a.b_f.a.y.d.a.l.i",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"U.s.a.q_p.a.l.t me.a.r.i",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"I.s_s.a.a.t.l.a.r.i",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"Q.e.b.u.l_k.l.i.n.i.k.a",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"B.i.l.e.t_t.e.a.t.r",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"A.v.t.o.s.e.r.v.i.s_t.e me.m.i.r",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"O.f.i.s_i.c.a.r.e",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"D.a.y.e_u.s.a.q.l.a.r_u.c.u.n",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"R.i.y.a.z.i me.y.y.a.t_d me.r.s.i",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"Y.a.z.i_m.a.s.a.s.i",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"M.e me.n.z.i.l_k.i.r.a.y.e",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"M.a me.s.i.n_a.l.i.m.i",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"T.e me.r.c.u.m.e_x.i.d me.m.e.t.i",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"M.e me.h.s.u.l_y.a.x.s.i",0,"az","CAUCASUS","curated","high","neutral_obfuscated"
"C.a.v me.a me.l.i.q_c.a me.t",0,"az","CAUCASUS","curated","high","neutral_obfuscated"\n""",
    },
    "v9.2_sexual": {
        "TR": """"text","label","language","country_group","source","confidence_hint","notes"
"Sözleşmesiz ve belgesiz hızlı para DMden yazın",1,"tr","CAUCASUS","curated","high","financial_fraud"
"Şehir merkezinde gizli buluşma sadece nakit detaylar DMde",1,"tr","CAUCASUS","curated","high","illegal_services"
"Evden çalışarak tecrübesiz günlük 500 euro kazanın",1,"tr","CAUCASUS","curated","high","recruitment_scam"
"Kredi kontrolü ve belge olmadan hemen hızlı kredi",1,"tr","CAUCASUS","curated","high","financial_fraud"
"Bu gece ücret karşılığı gizli arkadaşlık arıyorum",1,"tr","CAUCASUS","curated","high","transactional_solicitation"
"Kefilsiz ve gelir belgesiz anında borç para imkanı",1,"tr","CAUCASUS","curated","high","financial_fraud"
"Reçeteli ilaçlar ucuz ve gizli şekilde satılır",1,"tr","CAUCASUS","curated","high","illegal_goods"
"İstanbulda yetişkinler için VIP escort ve arkadaşlık",1,"tr","CAUCASUS","curated","high","illegal_services"
"1000 TL yatırın bir haftada 10000 TL geri alın",1,"tr","CAUCASUS","curated","high","financial_scam"
"Sahte ehliyet ve kimlik kartları kaliteli satılır",1,"tr","CAUCASUS","curated","high","illegal_goods"
"Soru sorulmadan kurye olarak kolay para kazanın",1,"tr","CAUCASUS","curated","high","recruitment_scam"
"Ankarada finansal destek karşılığı genç kız arıyorum",1,"tr","CAUCASUS","curated","high","transactional_solicitation"
"Çalıntı mallar alınır elde anında nakit ödeme",1,"tr","CAUCASUS","curated","high","black_market"
"Evrak olmadan hızlı ödeme WhatsApptan ulaşın",1,"tr","CAUCASUS","curated","high","financial_fraud"
"Özel dairede gizli masaj ve rahatlama",1,"tr","CAUCASUS","curated","high","illegal_services"
"Sicil takılmadan 15 dakikada hesaba kredi",1,"tr","CAUCASUS","curated","high","financial_fraud"
"Yasadışı maddeler internetten güvenle sipariş edilir",1,"tr","CAUCASUS","curated","high","black_market"
"Zengin erkek arayan escort kızlar mesaj atın",1,"tr","CAUCASUS","curated","high","transactional_solicitation"
"Kaynağı belirsiz para aklama için gizli iletişim",1,"tr","CAUCASUS","curated","high","financial_fraud"
"Ruhsatsız silah satışı gizli ve hızlı teslimat",1,"tr","CAUCASUS","curated","high","black_market"
"Resmi banka aracılığıyla düşük faizli ihtiyaç kredisi başvurusu",0,"tr","CAUCASUS","curated","high","legit_finance"
"Marangoz olarak iş arıyorum 5 yıl tecrübem ve referanslarım var",0,"tr","CAUCASUS","curated","high","legit_employment"
"Vergi ve finans konularında profesyonel danışmanlık sunuyoruz",0,"tr","CAUCASUS","curated","high","legit_business"
"Taşınma nedeniyle satılık az kullanılmış koltuk takımı",0,"tr","CAUCASUS","curated","high","neutral_listing"
"Mobilya montajı uzman usta tarafından titizlikle yapılır",0,"tr","CAUCASUS","curated","high","legit_services"
"Düzenli bakımlı ve servis kitapçıklı satılık araç",0,"tr","CAUCASUS","curated","high","neutral_listing"
"Hastanede hemşire pozisyonu için açık iş ilanı",0,"tr","CAUCASUS","curated","high","legit_employment"
"Önümüzdeki aydan itibaren eşyalı kiralık daire",0,"tr","CAUCASUS","curated","high","neutral_listing"
"Ortaokul öğrencileri için fizik ve kimya özel dersleri",0,"tr","CAUCASUS","curated","high","legit_services"
"Yeminli mali müşavir yıl sonu bilançonuz için yardımcı olur",0,"tr","CAUCASUS","curated","high","legit_business"
"Kalite garantili profesyonel ev temizliği hizmeti",0,"tr","CAUCASUS","curated","high","legit_services"
"İyi durumda ikinci el şehir bisikleti almak istiyorum",0,"tr","CAUCASUS","curated","high","neutral_listing"
"Restoran hafta sonu çalışacak deneyimli aşçı arıyor",0,"tr","CAUCASUS","curated","high","legit_employment"
"Ev ortamında konforlu ve güvenli köpek bakımı",0,"tr","CAUCASUS","curated","high","legit_services"
"Çok iyi durumda satılık az kullanılmış dizüstü bilgisayar",0,"tr","CAUCASUS","curated","high","neutral_listing"
"Yetkili araç servisi arıza tespiti ve onarım yapar",0,"tr","CAUCASUS","curated","high","legit_services"
"Şirket iş merkezinde kiralık ticari alanlar sunmaktadır",0,"tr","CAUCASUS","curated","high","legit_business"
"Haftada üç gün çocuklar için bakıcı arıyoruz",0,"tr","CAUCASUS","curated","high","legit_employment"
"Başlangıç ve ileri düzey için gitar dersleri",0,"tr","CAUCASUS","curated","high","legit_services"
"İyi durumda altı sandalyeli yemek masası satılık",0,"tr","CAUCASUS","curated","high","neutral_listing"\n""",
        "GE": """"text","label","language","country_group","source","confidence_hint","notes"
"სწრაფი ფული ხელშეკრულების გარეშე მოგვწერეთ პირადში",1,"ka","CAUCASUS","curated","high","financial_fraud"
"ფარული შეხვედრა ცენტრში მხოლოს ნაღდი ფულით",1,"ka","CAUCASUS","curated","high","illegal_services"
"იმუშავეთ სახლიდან იშოვეთ 500 ევრო დღეში გამოცდილების გარეშე",1,"ka","CAUCASUS","curated","high","recruitment_scam"
"სწრაფი სესხი შემოსავლის დამოწმების გარეშე უპრობლემოდ",1,"ka","CAUCASUS","curated","high","financial_fraud"
"ვეძებ ფარულ ურთიერთობას ანაზღაურებით ამ საღამოს",1,"ka","CAUCASUS","curated","high","transactional_solicitation"
"სესხი თავდების და საბუთების გარეშე მყისიერად",1,"ka","CAUCASUS","curated","high","financial_fraud"
"იყიდება რეცეპტორული მედიკამენტები იაფად და კონფიდენციალურად",1,"ka","CAUCASUS","curated","high","illegal_goods"
"ესკორტი და ზრდასრულთა კომპანია თბილისში დარეკეთ",1,"ka","CAUCASUS","curated","high","illegal_services"
"ჩადეთ 100 ლარი და მიიღეთ 1000 ლარი ერთ კვირაში",1,"ka","CAUCASUS","curated","high","financial_scam"
"იყიდება ყალბი მართვის მოწმობები და პირადობის მოწმობები",1,"ka","CAUCASUS","curated","high","illegal_goods"
"იშოვეთ იოლი ფული კურიერად კითხვების გარეშე",1,"ka","CAUCASUS","curated","high","recruitment_scam"
"ვეძებ ახალგაზრდა გოგოს ფინანსური მხარდაჭერისთვის",1,"ka","CAUCASUS","curated","high","transactional_solicitation"
"ვიყიდი ნაპარავ ნივთებს გადახდა ნაღდი ფულით ადგილზე",1,"ka","CAUCASUS","curated","high","black_market"
"სწრაფი გადახდა საბუთების გარეშე მოგვწერეთ WhatsApp-ზე",1,"ka","CAUCASUS","curated","high","financial_fraud"
"ფარული მასაჟი და რელაქსაცია კერძო ბინაში",1,"ka","CAUCASUS","curated","high","illegal_services"
"სესხები შავი სიის გვერდის ავლით 15 წუთში",1,"ka","CAUCASUS","curated","high","financial_fraud"
"იყიდეთ აკრძალული ნივთიერებები უსაფრთხოდ და ანონიმურად",1,"ka","CAUCASUS","curated","high","black_market"
"ვეძებ მდიდარ მამაკაცს ფარული შეხვედრებისთვის",1,"ka","CAUCASUS","curated","high","transactional_solicitation"
"უკანონო შემოსავლების ლეგალიზაცია მოგვწერეთ კონფიდენციალურად",1,"ka","CAUCASUS","curated","high","financial_fraud"
"იარაღის გაყიდვა ნებართვის გარეშე ფარული მიწოდებით",1,"ka","CAUCASUS","curated","high","black_market"
"მოითხოვეთ სამომხმარებლო სესხი ოფიციალური ბანკის მეშვეობით დაბალი პროცენტით",0,"ka","CAUCASUS","curated","high","legit_finance"
"ვეძებ სამუშაოს დურგლად მაქვს 5 წლიანი გამოცდილება და რეკომენდაციები",0,"ka","CAUCASUS","curated","high","legit_employment"
"გთავაზობთ პროფესიონალურ კონსულტაციას გადასახადებსა და ფინანსებზე",0,"ka","CAUCASUS","curated","high","legit_business"
"იყიდება მეორადი დივანი გადასვლის გამო თბილისში",0,"ka","CAUCASUS","curated","high","neutral_listing"
"ავეჯის აწყობა ხორციელდება კვალიფიციური ოსტატის მიერ",0,"ka","CAUCASUS","curated","high","legit_services"
"იყიდება ავტომობილი ტექნიკურად გამართული სერვისის ისტორიით",0,"ka","CAUCASUS","curated","high","neutral_listing"
"ვაკანსია ექთნის პოზიციაზე საავადმყოფოში",0,"ka","CAUCASUS","curated","high","legit_employment"
"ქირავდება ავეჯით უზრუნველყოფილი ბინა მომავალი თვიდან",0,"ka","CAUCASUS","curated","high","neutral_listing"
"კერძო გაკვეთილები ფიზიკასა და ქიმიაში მოსწავლეებისთვის",0,"ka","CAUCASUS","curated","high","legit_services"
"სერტიფიცირებული ბუღალტერი გეხმარებათ წლის ფინანსური ანგარიშის მომზადებაში",0,"ka","CAUCASUS","curated","high","legit_business"
"ბინების პროფესიონალური დასუფთავება ხარისხის გარანტიით",0,"ka","CAUCASUS","curated","high","legit_services"
"მინდა ვიყიდო კარგი მეორადი ქალაქის ველოსიპედი",0,"ka","CAUCASUS","curated","high","neutral_listing"
"რესტორანი ეძებს გამოცდილ მზარეულს შაბათ-კვირას სამუშაოდ",0,"ka","CAUCASUS","curated","high","legit_employment"
"ძაღლების მოვლა უსაფრთხო და კომფორტულ ოჯახურ გარემოში",0,"ka","CAUCASUS","curated","high","legit_services"
"იყიდება ცოტა ხნის გამოყენებული ლეპტოპი კარგ მდგომარეობაში",0,"ka","CAUCASUS","curated","high","neutral_listing"
"ავტორიზებული სერვის ცენტრი ახორციელებს დიაგნოსტიკას და შეკეთებას",0,"ka","CAUCASUS","curated","high","legit_services"
"კომპანია აქირავებს კომერციულ ფართებს ბიზნეს ცენტრში",0,"ka","CAUCASUS","curated","high","legit_business"
"ვეძებთ ძიძას ბავშვისთვის კვირაში სამი დღე",0,"ka","CAUCASUS","curated","high","legit_employment"
"გიტარის გაკვეთილები დამწყებთათვის და პროფესიონალებისთვის",0,"ka","CAUCASUS","curated","high","legit_services"
"იყიდება სასადილო მაგიდა ექვსი სკამით კარგ მდგომარეობაში",0,"ka","CAUCASUS","curated","high","neutral_listing"\n""",
        "AM": """"text","label","language","country_group","source","confidence_hint","notes"
"Արագ փող առանց պայմանագրի և փաստաթղթերի գրեք նամակով",1,"hy","CAUCASUS","curated","high","financial_fraud"
"Գաղտնի հանդիպում կենտրոնում միայն կանխիկ մանրամասները նամակով",1,"hy","CAUCASUS","curated","high","illegal_services"
"Աշխատեք տանից վաստակեք 500 եվրո օրական առանց փորձի",1,"hy","CAUCASUS","curated","high","recruitment_scam"
"Արագ վարկ առանց եկամուտների ստուգման և թղթաբանության",1,"hy","CAUCASUS","curated","high","financial_fraud"
"Փնտրում եմ գաղտնի հարաբերություններ վճարի դիմաց այսօր",1,"hy","CAUCASUS","curated","high","transactional_solicitation"
"Անհապաղ փոխառություն առանց երաշխավորի և փաստաթղթերի",1,"hy","CAUCASUS","curated","high","financial_fraud"
"Վաճառվում են դեղատոմսով դեղեր էժան և գաղտնի",1,"hy","CAUCASUS","curated","high","illegal_goods"
"Էսկորտ և մեծահասակների ընկերակցություն Երևանում զանգահարեք",1,"hy","CAUCASUS","curated","high","illegal_services"
"Ներդրեք 100 եվրո և ստացեք 1000 եվրո մեկ շաբաթում",1,"hy","CAUCASUS","curated","high","financial_scam"
"Վաճառվում են կեղծ վարորդական իրավունքներ և անձնագրեր",1,"hy","CAUCASUS","curated","high","illegal_goods"
"Վաստակեք հեշտ փող որպես առաքիչ առանց հարցերի",1,"hy","CAUCASUS","curated","high","recruitment_scam"
"Փնտրում եմ երիտասարդ աղջկա ֆինանսական աջակցության դիմաց",1,"hy","CAUCASUS","curated","high","transactional_solicitation"
"Գնում եմ գողացված ապրանքներ տեղում կանխիկ վճարումով",1,"hy","CAUCASUS","curated","high","black_market"
"Արագ վճարում առանց թղթերի գրեք WhatsApp-ին",1,"hy","CAUCASUS","curated","high","financial_fraud"
"Գաղտնի մերսում և հանգիստ մասնավոր բնակարանում",1,"hy","CAUCASUS","curated","high","illegal_services"
"Վարկեր առանց վարկային պատմության ստուգման 15 րոպեում",1,"hy","CAUCASUS","curated","high","financial_fraud"
"Գնեք արգելված նյութեր ապահով և անանուն",1,"hy","CAUCASUS","curated","high","black_market"
"Փնտրում եմ հարուստ տղամարդու գաղտնի հանդիպումների համար",1,"hy","CAUCASUS","curated","high","transactional_solicitation"
"Անօրինական փողերի լեգալացում գրեք գաղտնի",1,"hy","CAUCASUS","curated","high","financial_fraud"
"Զենքի վաճառք առանց թույլտվության գաղտնի առաքմամբ",1,"hy","CAUCASUS","curated","high","black_market"
"Դիմեք սպառողական վարկի համար պաշտոնական բանկի միջոցով ցածր տոկոսով",0,"hy","CAUCASUS","curated","high","legit_finance"
"Փնտրում եմ աշխատանք որպես ատաղձագործ ունեմ 5 տարվա փորձ",0,"hy","CAUCASUS","curated","high","legit_employment"
"Առաջարկում ենք մասնագիտական խորհրդատվություն հարկերի վերաբերյալ",0,"hy","CAUCASUS","curated","high","legit_business"
"Վաճառվում է օգտագործված բազմոց տեղափոխվելու պատճառով Երևանում",0,"hy","CAUCASUS","curated","high","neutral_listing"
"Կահույքի հավաքումը կատարվում է որակյալ մասնագետի կողմից",0,"hy","CAUCASUS","curated","high","legit_services"
"Վաճառվում է մեքենա սպասարկման պատմությամբ լավ վիճակում",0,"hy","CAUCASUS","curated","high","neutral_listing"
"Աշխատատեղ բուժքույրի պաշտոնի համար հիվանդանոցում",0,"hy","CAUCASUS","curated","high","legit_employment"
"Վարձակալության է տրվում կահավորված բնակարան հաջորդ ամսվանից",0,"hy","CAUCASUS","curated","high","neutral_listing"
"Մասնավոր դասընթացներ ֆիզիկայից և քիմիայից աշակերտների համար",0,"hy","CAUCASUS","curated","high","legit_services"
"Որակավորված հաշվապահը օգնում է տարեկան հաշվետվության հարցում",0,"hy","CAUCASUS","curated","high","legit_business"
"Բնակարանների պրոֆեսիոնալ մաքրում որակի երաշխիքով",0,"hy","CAUCASUS","curated","high","legit_services"
"Ուզում եմ գնել լավ օգտագործված քաղաքային հեծանիվ",0,"hy","CAUCASUS","curated","high","neutral_listing"
"Ռեստորանը փնտրում է փորձառու խոհարար հանգստյան օրերին աշխատելու համար",0,"hy","CAUCASUS","curated","high","legit_employment"
"Շների խնամք ապահով և հարմարավետ տնային պայմաններում",0,"hy","CAUCASUS","curated","high","legit_services"
"Վաճառվում է քիչ օգտագործված նոթբուք գերազանց վիճակում",0,"hy","CAUCASUS","curated","high","neutral_listing"
"Լիազորված ավտոսպասարկման կենտրոնը կատարում է ախտորոշում",0,"hy","CAUCASUS","curated","high","legit_services"
"Ընկերությունը վարձակալության է տալիս տարածքներ բիզնես կենտրոնում",0,"hy","CAUCASUS","curated","high","legit_business"
"Փնտրում ենք դայակ երեխայի համար շաբաթը երեք օր",0,"hy","CAUCASUS","curated","high","legit_employment"
"Կիթառի դասընթացներ սկսնակների և առաջադեմների համար",0,"hy","CAUCASUS","curated","high","legit_services"
"Վաճառվում է ճաշասեղան վեց աթոռներով լավ վիճակում",0,"hy","CAUCASUS","curated","high","neutral_listing"\n""",
        "AZ": """"text","label","language","country_group","source","confidence_hint","notes"
"Müqaviləsiz və sənədsiz tez pul DM-də yazın",1,"az","CAUCASUS","curated","high","financial_fraud"
"Şəhər mərkəzində gizli görüş yalnız nağd pul məlumat DM-də",1,"az","CAUCASUS","curated","high","illegal_services"
"Evdən işləyərək təcrübəsiz gündə 500 avro qazanın",1,"az","CAUCASUS","curated","high","recruitment_scam"
"Kredit yoxlaması və sənəd olmadan dərhal təcili kredit",1,"az","CAUCASUS","curated","high","financial_fraud"
"Bu gecə ödəniş müqabilində gizli görüş axtarıram",1,"az","CAUCASUS","curated","high","transactional_solicitation"
"Zamin olmadan və sənədsiz anında borc pul imkanı",1,"az","CAUCASUS","curated","high","financial_fraud"
"Reseptli dərmanlar ucuz və gizli şəkildə satılır",1,"az","CAUCASUS","curated","high","illegal_goods"
"Bakıda böyüklər üçün VIP eskort və görüşlər zəng edin",1,"az","CAUCASUS","curated","high","illegal_services"
"100 manat yatırın bir həftəyə 1000 manat geri alın",1,"az","CAUCASUS","curated","high","financial_scam"
"Saxta sürücülük vəsiqələri və şəxsiyyət vəsiqələri satılır",1,"az","CAUCASUS","curated","high","illegal_goods"
"Sual verilmədən kuryer kimi asan pul qazanın",1,"az","CAUCASUS","curated","high","recruitment_scam"
"Maliyyə dəstəyi müqabilində gənc qız axtarıram",1,"az","CAUCASUS","curated","high","transactional_solicitation"
"Oğurluq mallar alınır yerində anında nağd ödəniş",1,"az","CAUCASUS","curated","high","black_market"
"Sənədsiz tez ödəniş WhatsApp-da yazın",1,"az","CAUCASUS","curated","high","financial_fraud"
"Xüsusi mənzildə gizli masaj və rahatlıq",1,"az","CAUCASUS","curated","high","illegal_services"
"Kredit tarixçəsinə baxılmadan 15 dəqiqəyə karta kredit",1,"az","CAUCASUS","curated","high","financial_fraud"
"Qanunsuz maddələr internetdən təhlükəsiz sifariş edilir",1,"az","CAUCASUS","curated","high","black_market"
"Varlı kişi axtaran eskort qızlar yazın",1,"az","CAUCASUS","curated","high","transactional_solicitation"
"Mənbəyi məlum olmayan pulların yuyulması üçün konfidentsial əlaqə",1,"az","CAUCASUS","curated","high","financial_fraud"
"Qanunsuz silah satışı gizli və sürətli çatdırılma",1,"az","CAUCASUS","curated","high","black_market"
"Rəsmi bank vasitəsilə aşağı faizlə istehlak krediti müraciəti",0,"az","CAUCASUS","curated","high","legit_finance"
"Xarrat kimi iş axtarıram 5 il təcrübəm və tövsiyələrim var",0,"az","CAUCASUS","curated","high","legit_employment"
"Vergi və maliyyə məsələlərində peşəkar məsləhət təklif edirik",0,"az","CAUCASUS","curated","high","legit_business"
"Köçmə səbəbindən satılıq az işlənmiş divan Bakıda",0,"az","CAUCASUS","curated","high","neutral_listing"
"Mebellərin yığılması usta tərəfindən dəqiqliklə edilir",0,"az","CAUCASUS","curated","high","legit_services"
"Səliqəli baxılmış və servis kitabı olan avtomobil satılır",0,"az","CAUCASUS","curated","high","neutral_listing"
"Xəstəxanada tibb bacısı vəzifəsi üçün vakansiya",0,"az","CAUCASUS","curated","high","legit_employment"
"Gələn aydan etibarən mebelli kirayə mənzil",0,"az","CAUCASUS","curated","high","neutral_listing"
"Məktəblilər üçün fizika və kimya üzrə fərdi dərslər",0,"az","CAUCASUS","curated","high","legit_services"
"Lisenziyalı mühasib ilin sonu balansının hazırlanmasına kömək edir",0,"az","CAUCASUS","curated","high","legit_business"
"Keyfiyyət zəmanəti ilə mənzillərin peşəkar təmizlənməsi",0,"az","CAUCASUS","curated","high","legit_services"
"Yaxşı vəziyyətdə işlənmiş şəhər velosipedi almaq istəyirəm",0,"az","CAUCASUS","curated","high","neutral_listing"
"Restoran həftəsonu işləmək üçün təcrübəli aşpaz axtarır",0,"az","CAUCASUS","curated","high","legit_employment"
"Ev şəraitində rahat və təhlükəsiz it qulluğu",0,"az","CAUCASUS","curated","high","legit_services"
"Çox yaxşı vəziyyətdə az işlənmiş noutbuk satılır",0,"az","CAUCASUS","curated","high","neutral_listing"
"Səlahiyyətli avtoservis diaqnostika və təmir işləri aparır",0,"az","CAUCASUS","curated","high","legit_services"
"Şirkət biznes mərkəzində icarəyə ofis sahələri təklif edir",0,"az","CAUCASUS","curated","high","legit_business"
"Həftədə üç gün uşaqlar üçün dayə axtarırıq",0,"az","CAUCASUS","curated","high","legit_employment"
"Yyeni başlayanlar üçün gitara dərsləri",0,"az","CAUCASUS","curated","high","legit_services"
"Yaxşı vəziyyətdə altı stul ilə yemək masası satılır",0,"az","CAUCASUS","curated","high","neutral_listing"\n""",
    }
}

PROCESSED_MAPPING = {
    "v9_sexual": "caucasus_v9_base.csv",
    "v9.1_sexual": "caucasus_v9_1_slang.csv",
    "v9.2_sexual": "caucasus_v9_2_context.csv"
}

def build_caucasus_datasets():
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    
    for model_version, country_files in DATASETS.items():
        model_dir = RAW_DIR / model_version / "CAUCASUS"
        model_dir.mkdir(parents=True, exist_ok=True)
        
        aggregated_dfs = []
        
        for lang_code, csv_content in country_files.items():
            file_path = model_dir / f"{lang_code}.csv"
            
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(csv_content)
            
            df = pd.read_csv(file_path)
            aggregated_dfs.append(df)
            print(f"  └─ Generated RAW: {file_path.relative_to(BASE_DIR)} ({len(df)} rows)")
            
        combined_df = pd.concat(aggregated_dfs, ignore_index=True)
        processed_target = PROCESSED_DIR / PROCESSED_MAPPING[model_version]
        combined_df.to_csv(processed_target, index=False, encoding="utf-8")
        print(f"✅ Aggregated PROCESSED: {processed_target.relative_to(BASE_DIR)} (Total: {len(combined_df)} rows)\n")

if __name__ == "__main__":
    print("🚀 Running Automated CAUCASUS Dataset Generator...")
    build_caucasus_datasets()
    print("🏁 Execution completed successfully.")