#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Expanded Data Generator & Aggregator for NORDIC Cluster (v7, v7.1, v7.2)
Author: Maksym Nenashev (Systems Engineer)
"""

import sys
from pathlib import Path
import pandas as pd

# Определение базовой директории проекта
BASE_DIR = Path(__file__).resolve().parent.parent
RAW_DIR = BASE_DIR / "raw"
PROCESSED_DIR = BASE_DIR / "data" / "processed"

# Расширенные датасеты (7 колонок: text,label,language,country_group,source,confidence_hint,notes)
DATASETS = {
    "v7_sexual": {
        "SE": """"text","label","language","country_group","source","confidence_hint","notes"
"Jag ska döda dig din jävla idiot",1,"sv","NORDIC","curated","high","direct_threat"
"Jag vet var du bor, passa dig noga",1,"sv","NORDIC","curated","high","stalking_threat"
"Kan du skicka nakenbilder till mig",1,"sv","NORDIC","curated","high","explicit_request"
"Du är en jävla fitta och ett svin",1,"sv","NORDIC","curated","high","overt_insult"
"Jag ska slå sönder dig din jävel",1,"sv","NORDIC","curated","high","direct_threat"
"Skaffa ett liv din jävla förlorare",1,"sv","NORDIC","curated","high","overt_insult"
"Jag vill se dig naken nu",1,"sv","NORDIC","curated","high","explicit_request"
"Om du inte lyder kommer jag skada dig",1,"sv","NORDIC","curated","high","direct_threat"
"Du är en sjuk jävel som borde spärras in",1,"sv","NORDIC","curated","high","overt_insult"
"Erbjuder du sexuella tjänster mot betalning",1,"sv","NORDIC","curated","high","transactional_solicitation"
"Jag ska hitta din familj och göra er illa",1,"sv","NORDIC","curated","high","stalking_threat"
"Håll käften din jävla idiot",1,"sv","NORDIC","curated","high","overt_insult"
"Vill du ha sex med mig i natt",1,"sv","NORDIC","curated","high","explicit_request"
"Dra åt helvete din förbannade skit",1,"sv","NORDIC","curated","high","overt_insult"
"Jag väntar utanför ditt hus, kom ut",1,"sv","NORDIC","curated","high","stalking_threat"
"Du förtjänar att dö din skit",1,"sv","NORDIC","curated","high","direct_threat"
"Skicka dina privata bilder nu",1,"sv","NORDIC","curated","high","explicit_request"
"Jag tänker förstöra ditt liv fullständigt",1,"sv","NORDIC","curated","high","direct_threat"
"Sug min kuk din jävla fitta",1,"sv","NORDIC","curated","high","overt_insult"
"Du kommer att ångra att du föddes",1,"sv","NORDIC","curated","high","direct_threat"
"Säljer en begagnad cykel i gott skick",0,"sv","NORDIC","curated","high","neutral_listing"
"Tack för snabbt svar och utmärkt service",0,"sv","NORDIC","curated","high","neutral_communication"
"Kan vi boka ett möte imorgon klockan tio",0,"sv","NORDIC","curated","high","neutral_business"
"Önskar köpa ett matbord i ek",0,"sv","NORDIC","curated","high","neutral_listing"
"Hej, jag vill ställa en fråga om er tjänst",0,"sv","NORDIC","curated","high","neutral_query"
"Jag letar efter en lägenhet att hyra i Stockholm",0,"sv","NORDIC","curated","high","neutral_listing"
"Kan du skicka fakturan till min e-postadress",0,"sv","NORDIC","curated","high","neutral_business"
"Vi arrangerar en välgörenhetskonsert nästa helg",0,"sv","NORDIC","curated","high","neutral_communication"
"Boken var mycket intressant och rekommenderas varmt",0,"sv","NORDIC","curated","high","neutral_communication"
"Finns varan kvar eller är den redan såld",0,"sv","NORDIC","curated","high","neutral_query"
"Jag kommer att vara lite sen till mötet idag",0,"sv","NORDIC","curated","high","neutral_communication"
"Önskar hyra en bil under tre dagar i juli",0,"sv","NORDIC","curated","high","neutral_query"
"Tack för hjälpen, det var väldigt snällt av dig",0,"sv","NORDIC","curated","high","neutral_communication"
"Säljer barnkläder i storlek 92, helt nya",0,"sv","NORDIC","curated","high","neutral_listing"
"Vad är öppettiderna för er rullstolsanpassade entré",0,"sv","NORDIC","curated","high","neutral_query"
"Erbjuder tidsbokning för hälsokontroll på kliniken",0,"sv","NORDIC","curated","high","legit_services"
"Jag skulle vilja beställa två biljetter till teatern",0,"sv","NORDIC","curated","high","neutral_business"
"Hunden behöver en promenad varje eftermiddag",0,"sv","NORDIC","curated","high","neutral_communication"
"Kursen startar nästa måndag klockan nio",0,"sv","NORDIC","curated","high","neutral_business"
"Det var trevligt att träffas på konferensen",0,"sv","NORDIC","curated","high","neutral_communication"\n""",
        "DK": """"text","label","language","country_group","source","confidence_hint","notes"
"Du er en forfædelig idiot og en taber",1,"da","NORDIC","curated","high","overt_insult"
"Jeg ved hvor du bor, pas på dig selv",1,"da","NORDIC","curated","high","stalking_threat"
"Kan du sende mig nøgenbilleder nu",1,"da","NORDIC","curated","high","explicit_request"
"Jeg slår dig ihjel din skidespræller",1,"da","NORDIC","curated","high","direct_threat"
"Du er så grim og ubrugelig",1,"da","NORDIC","curated","high","overt_insult"
"Hold din kæft din lorte idiot",1,"da","NORDIC","curated","high","overt_insult"
"Jeg vil se dig nøgen med det samme",1,"da","NORDIC","curated","high","explicit_request"
"Hvis du ikke svarer kommer jeg efter dig",1,"da","NORDIC","curated","high","direct_threat"
"Du er en syg nar der burde skamme sig",1,"da","NORDIC","curated","high","overt_insult"
"Tilbyder du sex mod betaling i aften",1,"da","NORDIC","curated","high","transactional_solicitation"
"Jeg finder dine børn og gør dem ondt",1,"da","NORDIC","curated","high","stalking_threat"
"Skrid ad helvede til din klaptorsk",1,"da","NORDIC","curated","high","overt_insult"
"Vil du have sex med mig nu",1,"da","NORDIC","curated","high","explicit_request"
"Du er en skamplet for alle herinde",1,"da","NORDIC","curated","high","overt_insult"
"Jeg venter på dig uden for dit hus",1,"da","NORDIC","curated","high","stalking_threat"
"Du fortjener at dø din lort",1,"da","NORDIC","curated","high","direct_threat"
"Send dine private billeder med det samme",1,"da","NORDIC","curated","high","explicit_request"
"Jeg vil ødelægge dit liv fuldstændigt",1,"da","NORDIC","curated","high","direct_threat"
"Sut min pik din skide kælling",1,"da","NORDIC","curated","high","overt_insult"
"Du vil fortryde at du nogensinde blev født",1,"da","NORDIC","curated","high","direct_threat"
"Sælger en brugt cykel i god stand",0,"da","NORDIC","curated","high","neutral_listing"
"Tak for hurtigt svar og god betjening",0,"da","NORDIC","curated","high","neutral_communication"
"Hvornår åbner butikken i dag",0,"da","NORDIC","curated","high","neutral_query"
"Jeg vil gerne bestille et bord til to",0,"da","NORDIC","curated","high","neutral_business"
"Ønsker at købe en brugt sofa",0,"da","NORDIC","curated","high","neutral_listing"
"Jeg leder efter en lejlighed i København",0,"da","NORDIC","curated","high","neutral_listing"
"Kan du sende regningen til min e-mail",0,"da","NORDIC","curated","high","neutral_business"
"Vi arrangerer et loppemarked på søndag",0,"da","NORDIC","curated","high","neutral_communication"
"Bogen var rigtig god og spændende",0,"da","NORDIC","curated","high","neutral_communication"
"Er varen stadig til salg i butikken",0,"da","NORDIC","curated","high","neutral_query"
"Jeg bliver lidt forsinket til vores aftale",0,"da","NORDIC","curated","high","neutral_communication"
"Ønsker at leje en bil i weekenden",0,"da","NORDIC","curated","high","neutral_query"
"Mange tak for hjælpen i dag",0,"da","NORDIC","curated","high","neutral_communication"
"Sælger børnetøj i str 92 helt ubrugt",0,"da","NORDIC","curated","high","neutral_listing"
"Hvad er åbningstiderne for jeres kundeservice",0,"da","NORDIC","curated","high","neutral_query"
"Tilbyder tidsbestilling til helbredstjek på klinikken",0,"da","NORDIC","curated","high","legit_services"
"Jeg vil gerne bestille to billetter til teateret",0,"da","NORDIC","curated","high","neutral_business"
"Hunden skal luftes hver eftermiddag",0,"da","NORDIC","curated","high","neutral_communication"
"Kurset starter næste mandag klokken ni",0,"da","NORDIC","curated","high","neutral_business"
"Det var hyggeligt at møde dig på konferencen",0,"da","NORDIC","curated","high","neutral_communication"\n""",
        "NO": """"text","label","language","country_group","source","confidence_hint","notes"
"Du er en jævla idiot og en taper",1,"no","NORDIC","curated","high","overt_insult"
"Jeg vet hvor du bor, pass deg",1,"no","NORDIC","curated","high","stalking_threat"
"Kan du sende meg nakenbilder takk",1,"no","NORDIC","curated","high","explicit_request"
"Jeg skal banke deg din drittsekk",1,"no","NORDIC","curated","high","direct_threat"
"Du er så jævlig stygg og ubrukelig",1,"no","NORDIC","curated","high","overt_insult"
"Hold kjeft din forbannede idiot",1,"no","NORDIC","curated","high","overt_insult"
"Jeg vil se deg naken med en gang",1,"no","NORDIC","curated","high","explicit_request"
"Hvis du ikke holder opp skal jeg skade deg",1,"no","NORDIC","curated","high","direct_threat"
"Du er en syk jævel som burde låses inne",1,"no","NORDIC","curated","high","overt_insult"
"Tilbyr du seksuelle tjenester mot penger",1,"no","NORDIC","curated","high","transactional_solicitation"
"Jeg vet hvilken skoler barna dine går på",1,"no","NORDIC","curated","high","stalking_threat"
"Pill deg vekk din jævla hestkuk",1,"no","NORDIC","curated","high","overt_insult"
"Vil du ha sex med meg i kveld",1,"no","NORDIC","curated","high","explicit_request"
"Du er en skam for hele familien din",1,"no","NORDIC","curated","high","overt_insult"
"Jeg står utenfor døren din akkurat nå",1,"no","NORDIC","curated","high","stalking_threat"
"Du fortjener å dø din dritt",1,"no","NORDIC","curated","high","direct_threat"
"Send dine private bilder med en gang",1,"no","NORDIC","curated","high","explicit_request"
"Jeg skal ødelegge livet ditt fullstendig",1,"no","NORDIC","curated","high","direct_threat"
"Sug kuken min din jævla fitte",1,"no","NORDIC","curated","high","overt_insult"
"Du kommer til å angre på at du ble født",1,"no","NORDIC","curated","high","direct_threat"
"Selger en brukt sykkel i god stand",0,"no","NORDIC","curated","high","neutral_listing"
"Takk for raskt svar og god hjelp",0,"no","NORDIC","curated","high","neutral_communication"
"Ønsker å kjøpe spisebord i tre",0,"no","NORDIC","curated","high","neutral_listing"
"Kan vi avtale et møte på mandag",0,"no","NORDIC","curated","high","neutral_business"
"Hei, når åpner butikken i morgen",0,"no","NORDIC","curated","high","neutral_query"
"Jeg leter etter en leilighet til leie i Oslo",0,"no","NORDIC","curated","high","neutral_listing"
"Kan du sende fakturaen på e-post",0,"no","NORDIC","curated","high","neutral_business"
"Vi arrangerer dugnad i borettslaget neste uke",0,"no","NORDIC","curated","high","neutral_communication"
"Boken var veldig lærerik og interessant",0,"no","NORDIC","curated","high","neutral_communication"
"Er denne varen fortsatt til salgs",0,"no","NORDIC","curated","high","neutral_query"
"Jeg blir dessverre litt forsinket i dag",0,"no","NORDIC","curated","high","neutral_communication"
"Ønsker å leie en hytte i fjellet til helgen",0,"no","NORDIC","curated","high","neutral_query"
"Tusen takk for god støtte og hjelp",0,"no","NORDIC","curated","high","neutral_communication"
"Selger barneklær i størrelse 92 helt nytt",0,"no","NORDIC","curated","high","neutral_listing"
"Hva er åpningstidene for kundesenteret",0,"no","NORDIC","curated","high","neutral_query"
"Tilbyr timebestilling for helsesjekk på klinikken",0,"no","NORDIC","curated","high","legit_services"
"Jeg vil gjerne bestille to billetter til teateret",0,"no","NORDIC","curated","high","neutral_business"
"Hunden trenger en luftetur hver ettermiddag",0,"no","NORDIC","curated","high","neutral_communication"
"Kurset starter neste mandag klokken ni",0,"no","NORDIC","curated","high","neutral_business"
"Det var hyggelig å møte deg på konferansen",0,"no","NORDIC","curated","high","neutral_communication"\n""",
        "FI": """"text","label","language","country_group","source","confidence_hint","notes"
"Tapan sinut senkin vitun hullu",1,"fi","NORDIC","curated","high","direct_threat"
"Mene helvettiin senkin kusipää",1,"fi","NORDIC","curated","high","overt_insult"
"Lähetä minulle alastonkuvia heti",1,"fi","NORDIC","curated","high","explicit_request"
"Tiedän missä asut, katso taaksesi",1,"fi","NORDIC","curated","high","stalking_threat"
"Olet täydellinen paskiainen ja idiootti",1,"fi","NORDIC","curated","high","overt_insult"
"Turpa kiinni senkin vitun paskiainen",1,"fi","NORDIC","curated","high","overt_insult"
"Haluatko harrastaa seksia kanssani tänään",1,"fi","NORDIC","curated","high","explicit_request"
"Jos et tottele niin vedän sinua turpaan",1,"fi","NORDIC","curated","high","direct_threat"
"Olet sairas paskiainen joka sietäisi kuolla",1,"fi","NORDIC","curated","high","overt_insult"
"Tarjoatko seksipalveluja rahaa vastaan",1,"fi","NORDIC","curated","high","transactional_solicitation"
"Etsin sinut käsiini ja hoidan homman",1,"fi","NORDIC","curated","high","stalking_threat"
"Painu vittuun senkin saatanan lehmä",1,"fi","NORDIC","curated","high","overt_insult"
"Haluan nähdä sinut alasti heti paikalla",1,"fi","NORDIC","curated","high","explicit_request"
"Olet turha ihmisroska ja paskiainen",1,"fi","NORDIC","curated","high","overt_insult"
"Olen talosi ulkopuolella, tule ulos",1,"fi","NORDIC","curated","high","stalking_threat"
"Ansaitset kuolla senkin vitun paskiainen",1,"fi","NORDIC","curated","high","direct_threat"
"Lähetä yksityisiä kuviasi heti tänne",1,"fi","NORDIC","curated","high","explicit_request"
"Tulen tuhoamaan elämäsi täysin",1,"fi","NORDIC","curated","high","direct_threat"
"Ime munaa senkin vitun huora",1,"fi","NORDIC","curated","high","overt_insult"
"Tuot kadumaan sitä että synnyit",1,"fi","NORDIC","curated","high","direct_threat"
"Myydään käytetty polkupyörä hyvässä kunnossa",0,"fi","NORDIC","curated","high","neutral_listing"
"Kiitos nopeasta vastauksesta ja hyvästä palvelusta",0,"fi","NORDIC","curated","high","neutral_communication"
"Mitä kello on tänään Oulussa",0,"fi","NORDIC","curated","high","neutral_query"
"Haluaisin varata ajan huomiselle",0,"fi","NORDIC","curated","high","neutral_business"
"Ostetaan puinen ruokapöytä ja tuolit",0,"fi","NORDIC","curated","high","neutral_listing"
"Etsin vuokra-asuntoa Helsingin keskustasta",0,"fi","NORDIC","curated","high","neutral_listing"
"Voitko lähettää laskun sähköpostitse",0,"fi","NORDIC","curated","high","neutral_business"
"Järjestämme kirpputorin ensi viikonloppuna",0,"fi","NORDIC","curated","high","neutral_communication"
"Kirja oli erittäin mielenkiintoinen ja hyödyllinen",0,"fi","NORDIC","curated","high","neutral_communication"
"Onko tämä tuote vielä vapaana",0,"fi","NORDIC","curated","high","neutral_query"
"Olen valitettavasti hieman myöhässä kokouksesta",0,"fi","NORDIC","curated","high","neutral_communication"
"Haluaisin vuokrata mökin viikonlopuksi",0,"fi","NORDIC","curated","high","neutral_query"
"Paljon kiitoksia avustanne ja tuestanne",0,"fi","NORDIC","curated","high","neutral_communication"
"Myydään lastenvaatteita kokoa 92 käyttämättömiä",0,"fi","NORDIC","curated","high","neutral_listing"
"Mikä on asiakaspalvelunne puhelinnumero",0,"fi","NORDIC","curated","high","neutral_query"
"Tarjoamme ajanvarausta terveystarkastukseen klinikalla",0,"fi","NORDIC","curated","high","legit_services"
"Haluaisin tilata kaksi lippua teatteriin",0,"fi","NORDIC","curated","high","neutral_business"
"Koira tarvitsee lenkin joka iltapäivä",0,"fi","NORDIC","curated","high","neutral_communication"
"Kurssi alkaa ensi maanantaina klo yhdeksän",0,"fi","NORDIC","curated","high","neutral_business"
"Oli mukava tavata sinut konferenssissa",0,"fi","NORDIC","curated","high","neutral_communication"\n""",
    },
    "v7.1_sexual": {
        "SE": """"text","label","language","country_group","source","confidence_hint","notes"
"j_a_v_l_a_i_d_i_o_t",1,"sv","NORDIC","curated","high","obfuscation_spaces"
"f.u.c.k.i.n.g_f.i.t.t.a",1,"sv","NORDIC","curated","high","obfuscation_dots"
"j4vla 1d10t n4k3n",1,"sv","NORDIC","curated","high","leet_speak"
"k_u_n_t_i_s_h_b_a_s_t_a_r_d",1,"sv","NORDIC","curated","high","obfuscation_spaces"
"jævla fitteisääää",1,"sv","NORDIC","curated","high","slang_exaggeration"
"d_i_n_f_u_c_k_i_n_g_s_v_i_n",1,"sv","NORDIC","curated","high","obfuscation_spaces"
"s_k_i_c_k_a_n_a_k_e_n",1,"sv","NORDIC","curated","high","obfuscation_spaces"
"d00da d!g f!tt4",1,"sv","NORDIC","curated","high","leet_speak"
"f.i.t.t.u.n_j.a.v.e.l",1,"sv","NORDIC","curated","high","obfuscation_dots"
"s_l_a_s_o_n_d_e_r_d_i_g",1,"sv","NORDIC","curated","high","obfuscation_spaces"
"h_a_l_l_k_a_f_t_e_n",1,"sv","NORDIC","curated","high","obfuscation_spaces"
"f_a_n_s_j_a_v_e_l",1,"sv","NORDIC","curated","high","obfuscation_spaces"
"n.a.k.e.n.b.i.l.d.e.r",1,"sv","NORDIC","curated","high","obfuscation_dots"
"j_a_v_l_a_s_v_i_n",1,"sv","NORDIC","curated","high","obfuscation_spaces"
"s_u_g_m_i_n_k_u_k",1,"sv","NORDIC","curated","high","obfuscation_spaces"
"d.ö.d.a_d.i.g_s.v.i.n",1,"sv","NORDIC","curated","high","obfuscation_dots"
"f!tt4_j4vl4_s_v_i_n",1,"sv","NORDIC","curated","high","leet_speak"
"h_a_l_l_k_a_f_t_e_n_d_i_n_f_i_t_t_a",1,"sv","NORDIC","curated","high","obfuscation_spaces"
"n4k3nb!ld3r_n00w",1,"sv","NORDIC","curated","high","leet_speak"
"s.k.a.d.a_d.i.g_j.a.v.e.l",1,"sv","NORDIC","curated","high","obfuscation_dots"
"S.ä.l.j.e.r_c.y.k.e.l_f.ö.r_1.0.0.0_k.r",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"T.a.c.k_f.ö.r_i.d.a.g",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"M.ö.t.e_i.m.o.r.g.o.n_k.l_1.0",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"V.ä.l.k.o.m.m.e.n_t.i.l.l_o.s.s",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"H.e.j_v.a.d_k.o.s.t.a.r_d.e.t",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"S.k.i.c.k.a_f.a.k.t.u.r.a.n_t.a.c.k",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"B.o.k.a_b.o.r.d_f.ö.r_t.v.å",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"S.ä.l.j.e.s_f.i.n_s.o.f.f.a",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"L.ä.g.e.n.h.e.t_i_S.t.o.c.k.h.o.l.m",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"F.i.n.n.s_v.a.r.a.n_k.v.a.r",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"R.i.n.g_m.i.g_i_d.a.g",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"O.n.s.k.a.r_k.o.p.a_b.i.l",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"B.a.r.n_k.l.a.d.e.r_s.a.l.j.e.s",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"T.a.c.k_f.o.r_h.j.a.l.p.e.n",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"V.a.l.k.o.m.m.e.n_h.e.m",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"B.e.s.t.ä.l.l.a_b.i.l.j.e.t.t.e.r",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"C.y.k.e.l_t.i.l.l_s.a.l.u",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"H.ä.l.s.o.k.o.n.t.r.o.l.l_i_d.a.g",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"L.ä.x.h.j.ä.l.p_i_m.a.t.e.m.a.t.i.k",0,"sv","NORDIC","curated","high","neutral_obfuscated"
"F.l.y.t.t.s.t.ä.d.n.i.n.g_u.t.f.ö.r.s",0,"sv","NORDIC","curated","high","neutral_obfuscated"\n""",
        "DK": """"text","label","language","country_group","source","confidence_hint","notes"
"f_u_c_k_i_n_g_t_a_b_e_r",1,"da","NORDIC","curated","high","obfuscation_spaces"
"s.k.i.d.e_i.d.i.o.t",1,"da","NORDIC","curated","high","obfuscation_dots"
"s_k.i_d.e_s_p.r_æ_l_l_e_r",1,"da","NORDIC","curated","high","obfuscation_mixed"
"f0rf43d3l1g 1d10t",1,"da","NORDIC","curated","high","leet_speak"
"l.o.r.t.e.s.æ.k.k.e.n",1,"da","NORDIC","curated","high","obfuscation_dots"
"f_u_c_k_d.i.g_n.a.r",1,"da","NORDIC","curated","high","obfuscation_mixed"
"n_ø_g_e_n_b_i_l_l_e_d_e_r",1,"da","NORDIC","curated","high","obfuscation_spaces"
"s_l_å_r_d_i_g_i_h_j_e_l",1,"da","NORDIC","curated","high","obfuscation_spaces"
"k_l_a_p_t_o_r_s_k_e_n",1,"da","NORDIC","curated","high","obfuscation_spaces"
"s_k_r_i_d_a_d_h_e_l_v_e_d_e",1,"da","NORDIC","curated","high","obfuscation_spaces"
"f_u_c_k_i_n_g_k_l_a_p_t_o_r_s_k",1,"da","NORDIC","curated","high","obfuscation_spaces"
"n_u_g_e_n_b_i_l_d_e_r",1,"da","NORDIC","curated","high","obfuscation_spaces"
"s.k.i.d.e.s.u.g.e.n",1,"da","NORDIC","curated","high","obfuscation_dots"
"f.u.c.k.l.o.r.t.e.n.a.r",1,"da","NORDIC","curated","high","obfuscation_dots"
"l_o_r_t_e_i_d_i_o_t",1,"da","NORDIC","curated","high","obfuscation_spaces"
"s_l_a_r_d_i_g_i_h_j_e_l_l",1,"da","NORDIC","curated","high","obfuscation_spaces"
"f0rf43d3l1g_kæll1ng",1,"da","NORDIC","curated","high","leet_speak"
"h_o_l_d_k_æ_f_t_l_o_r_t",1,"da","NORDIC","curated","high","obfuscation_spaces"
"n.ø.g.e.n.b.i.l.l.e.d.e.r_n.u",1,"da","NORDIC","curated","high","obfuscation_dots"
"ø.d.e.l.æ.g.g.e_d.i.t_l.i.v",1,"da","NORDIC","curated","high","obfuscation_dots"
"G.o.d_d.a.g_o.g_v.e.l.k.o.m.m.e.n",0,"da","NORDIC","curated","high","neutral_obfuscated"
"S.æ.l.g.e.s_b.i.l_b.r.u.g.t",0,"da","NORDIC","curated","high","neutral_obfuscated"
"T.a.k_f.o.r_h.j.æ.l.p.e.n",0,"da","NORDIC","curated","high","neutral_obfuscated"
"B.u.t.i.k.k.e.n_å.p.n.e.r_n.å",0,"da","NORDIC","curated","high","neutral_obfuscated"
"V.i_ø.n.s.k.e.r_e.n_g.o.d_d.a.g",0,"da","NORDIC","curated","high","neutral_obfuscated"
"S.e.n.d_r.e.g.n.i.n.g.e.n_t.a.k",0,"da","NORDIC","curated","high","neutral_obfuscated"
"B.e.s.t.i.l_b.o.r.d_i_d.a.g",0,"da","NORDIC","curated","high","neutral_obfuscated"
"K.ø.b_e.n_b.r.u.g.t_c.y.k.e.l",0,"da","NORDIC","curated","high","neutral_obfuscated"
"L.e.j.l.i.g.h.e.d_i_K.ø.b.e.n.h.a.v.n",0,"da","NORDIC","curated","high","neutral_obfuscated"
"V.a.r.e.n_e.r_t.i.l_s.a.l.g",0,"da","NORDIC","curated","high","neutral_obfuscated"
"R.i.n.g_t.i.l_o.s.s_i_d.a.g",0,"da","NORDIC","curated","high","neutral_obfuscated"
"Ø.n.s.k.e.r_k.ø.b_a.f_b.i.l",0,"da","NORDIC","curated","high","neutral_obfuscated"
"B.ø.r.n.e.t.ø.j_t.i.l_s.a.l.g",0,"da","NORDIC","curated","high","neutral_obfuscated"
"M.a.n.g.e_t.a.k_f.o.r_i_d.a.g",0,"da","NORDIC","curated","high","neutral_obfuscated"
"V.e.l.k.o.m.m.e.n_t.i.l_b.u.t.i.k",0,"da","NORDIC","curated","high","neutral_obfuscated"
"B.e.s.t.i.l_b.i.l.l.e.t.t.e.r_n.å",0,"da","NORDIC","curated","high","neutral_obfuscated"
"C.y.k.e.l_t.i.l_s.a.l.g_b.i.l.l.i.g",0,"da","NORDIC","curated","high","neutral_obfuscated"
"H.e.l.b.r.e.d.s.t.j.e.k_p.å_k.l.i.n.i.k.k.e.n",0,"da","NORDIC","curated","high","neutral_obfuscated"
"L.e.k.t.i.e.h.j.æ.l.p_i_e.n.g.e.l.s.k",0,"da","NORDIC","curated","high","neutral_obfuscated"
"F.l.y.t.t.e.r.e.n.g.ø.r.i.n.g_u.d.f.ø.r.e.s",0,"da","NORDIC","curated","high","neutral_obfuscated"\n""",
        "NO": """"text","label","language","country_group","source","confidence_hint","notes"
"j.æ.v.l.i.g_t.a.p.e.r",1,"no","NORDIC","curated","high","obfuscation_dots"
"f.u.c.k.u.b.r.u.k.e.l.i.g",1,"no","NORDIC","curated","high","obfuscation_dots"
"j_æ_v_l_a_d_r_i_t_t_s_e_k_k",1,"no","NORDIC","curated","high","obfuscation_spaces"
"h.e.l.v.e.t.e.s_f.i.t.t.e",1,"no","NORDIC","curated","high","obfuscation_dots"
"j3vl4 1d10t p4ss d3g",1,"no","NORDIC","curated","high","leet_speak"
"d_r_i_t_t_s_e_k_k_e_n",1,"no","NORDIC","curated","high","obfuscation_spaces"
"n_a_k_e_n_b_i_l_l_e_d_e_r_n_u",1,"no","NORDIC","curated","high","obfuscation_spaces"
"j_æ_v_l_a_h_e_s_t_k_u_k",1,"no","NORDIC","curated","high","obfuscation_spaces"
"f_u_c_k_i_n_g_t_a_p_e_r",1,"no","NORDIC","curated","high","obfuscation_spaces"
"s_k_a_l_b_a_n_k_e_d_e_g",1,"no","NORDIC","curated","high","obfuscation_spaces"
"d.i.n.f.o.r.b.a.n.n.e.d.e.i.d.i.o.t",1,"no","NORDIC","curated","high","obfuscation_dots"
"p_i_l_l_d_e_g_v_e_k_k",1,"no","NORDIC","curated","high","obfuscation_spaces"
"s_t_y_g_g_e_j_æ_v_e_l",1,"no","NORDIC","curated","high","obfuscation_spaces"
"n_a_k_e_n_b_i_l_d_e",1,"no","NORDIC","curated","high","obfuscation_spaces"
"f.u.c.k.j.æ.v.e.l",1,"no","NORDIC","curated","high","obfuscation_dots"
"s_k_a_l_ø_d_e_l_e_g_g_e_d_e_g",1,"no","NORDIC","curated","high","obfuscation_spaces"
"f!tt3_j3vl4_d_r_i_t_t",1,"no","NORDIC","curated","high","leet_speak"
"h_o_l_d_k_j_e_f_t_d_r_i_t_t",1,"no","NORDIC","curated","high","obfuscation_spaces"
"n.a.k.e.n.b.i.l.d.e.r_n.å",1,"no","NORDIC","curated","high","obfuscation_dots"
"ø.d.e.l.e.g.g.e_l.i.v.e.t_d.i.t.t",1,"no","NORDIC","curated","high","obfuscation_dots"
"T.a.k.k_f.o.r_h.j.e.l.p.e.n",0,"no","NORDIC","curated","high","neutral_obfuscated"
"S.e.l.g.e.r_s.y.k.k.e.l_f.i.n",0,"no","NORDIC","curated","high","neutral_obfuscated"
"G.o.d_m.o.r.g.e.n_a.l.l.e",0,"no","NORDIC","curated","high","neutral_obfuscated"
"M.ø.t.e_p.å_m.a.n.d.a.g",0,"no","NORDIC","curated","high","neutral_obfuscated"
"H.a_e.n_f.i.n_d.a.g",0,"no","NORDIC","curated","high","neutral_obfuscated"
"S.e.n.d_f.a.k.t.u.r.a_p.å_e.p.o.s.t",0,"no","NORDIC","curated","high","neutral_obfuscated"
"B.e.s.t.i.l.l_b.o.r.d_i_d.a.g",0,"no","NORDIC","curated","high","neutral_obfuscated"
"K.j.ø.p.e_b.r.u.k.t_s.o.f.a",0,"no","NORDIC","curated","high","neutral_obfuscated"
"L.e.i.l.i.g.h.e.t_i_O.s.l.o",0,"no","NORDIC","curated","high","neutral_obfuscated"
"E.r_d.e.t.t.e_t.i.l_s.a.l.g.s",0,"no","NORDIC","curated","high","neutral_obfuscated"
"R.i.n.g_m.e.g_i_d.a.g",0,"no","NORDIC","curated","high","neutral_obfuscated"
"Ø.n.s.k.e.r_å_l.e.i.e_h.y.t.t.e",0,"no","NORDIC","curated","high","neutral_obfuscated"
"B.a.r.n.e.k.l.æ.r_s.e.l.g.e.s",0,"no","NORDIC","curated","high","neutral_obfuscated"
"T.u.s.e.n_t.a.k.k_f.o.r_h.j.e.l.p",0,"no","NORDIC","curated","high","neutral_obfuscated"
"V.e.l.k.o.m.m.e.n_t.i.l_o.s.s",0,"no","NORDIC","curated","high","neutral_obfuscated"
"B.e.s.t.i.l.l_b.i.l.l.e.t.t.e.r_n.å",0,"no","NORDIC","curated","high","neutral_obfuscated"
"S.y.k.k.e.l_t.i.l_s.a.l.g.s_b.i.l.l.i.g",0,"no","NORDIC","curated","high","neutral_obfuscated"
"H.e.l.s.e.s.j.e.k.k_p.å_k.l.i.n.i.k.k.e.n",0,"no","NORDIC","curated","high","neutral_obfuscated"
"L.e.k.s.e.h.j.e.l.p_i_r.e.a.l.f.a.g",0,"no","NORDIC","curated","high","neutral_obfuscated"
"F.l.y.t.t.e.v.a.s.k_u.t.f.ø.r.e.s",0,"no","NORDIC","curated","high","neutral_obfuscated"\n""",
        "FI": """"text","label","language","country_group","source","confidence_hint","notes"
"v.i.t.u.n_k.u.s.i.p.a.a",1,"fi","NORDIC","curated","high","obfuscation_dots"
"v!tun p@skahousu",1,"fi","NORDIC","curated","high","leet_speak"
"v_i_t_t_u_n_l_a_p_s_i",1,"fi","NORDIC","curated","high","agglutination_obfuscated"
"k_u_s_i_p_a_a_n_e_n",1,"fi","NORDIC","curated","high","agglutination_obfuscated"
"p.a.s.k.a.p.ä.ä_i.d.i.o.o.t.t.i",1,"fi","NORDIC","curated","high","obfuscation_dots"
"a.l.a.s.t.o.n.k.u.v.a",1,"fi","NORDIC","curated","high","obfuscation_dots"
"v_i_t_u_n_p_a_s_k_i_a_i_n_e_n",1,"fi","NORDIC","curated","high","obfuscation_spaces"
"t_a_p_a_n_s_i_n_u_t",1,"fi","NORDIC","curated","high","obfuscation_spaces"
"m_e_n_e_h_e_l_v_e_t_t_i_i_n",1,"fi","NORDIC","curated","high","obfuscation_spaces"
"p_a_i_n_u_v_i_t_t_u_u_n",1,"fi","NORDIC","curated","high","obfuscation_spaces"
"s_a_a_t_a_n_a_n_h_u_l_l_u",1,"fi","NORDIC","curated","high","obfuscation_spaces"
"a_l_a_s_t_o_n_k_u_v_i_a",1,"fi","NORDIC","curated","high","obfuscation_spaces"
"k_u_s_i_p_a_a_i_d_i_o_o_t_t_i",1,"fi","NORDIC","curated","high","obfuscation_spaces"
"v_i_t_u_n_h_u_o_r_a",1,"fi","NORDIC","curated","high","obfuscation_spaces"
"p_a_s_k_a_i_m_i_s_r_o_s_k_a",1,"fi","NORDIC","curated","high","obfuscation_spaces"
"t_u_h_o_a_n_e_l_a_m_a_s_i",1,"fi","NORDIC","curated","high","obfuscation_spaces"
"v!tun_h0ur4_i.d.i.o.o.t.t.i",1,"fi","NORDIC","curated","high","leet_speak"
"t.u.r.p.a.a.n_v.e.d.ä.n",1,"fi","NORDIC","curated","high","obfuscation_dots"
"a.l.a.s.t.i_h.e.t.i",1,"fi","NORDIC","curated","high","obfuscation_dots"
"k_u_o.l.e_p_a_s_k_a",1,"fi","NORDIC","curated","high","obfuscation_mixed"
"M.y.y.d.ä.ä.n_t.a.l.o_O.u.l.u.s.s.a",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"K.i.i.t.o.s_p.a.l.j.o.n",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"M.e.r.k.i.t.t.ä.v.ä.ä_p.ä.i.v.ä.ä",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"H.y.v.ä.ä_h.u.o.m.e.n.t.a",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"T.e.r.v.e.t.u.l.o.a_m.e.i.l.l.e",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"L.ä.h.e.t.ä_l.a.s.k.u_s.ä.h.k.ö.p.o.s.t.i.i.n",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"V.a.r.a.a_a.j.a_h.u.o.m.e.n.n.a",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"O.s.t.e.t.a.a.n_p.ö.y.t.ä",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"V.u.o.k.r.a_a.s.u.n.t.o_H.e.l.s.i.n.g.i",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"O.n.k.o_t.u.o.t.e_v.a.p.a.a",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"S.o.i.t.a_m.i.n.u.l.l.e_t.ä.n.ä.ä.n",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"V.u.o.k.r.a.t.a.a.n_m.ö.k.k.i",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"L.a.s.t.e.n_v.a.a.t.t.e.i.t.a_m.y.y.d.ä.ä.n",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"P.a.l.j.o.n_k.i.i.t.o.k.s.i.a",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"H.y.v.ä.ä_p.ä.i.v.ä.ä_k.a.i.k.i.l.l.e",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"T.i.l.a.a_l.i.p.u.t_n.y.t",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"P.o.l.k.u.p.ö.y.r.ä_m.y.y.d.ä.ä.n",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"T.e.r.v.e.y.s.t.a.r.k.a.s.t.u.s_k.l.i.n.i.k.a.l.l.a",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"M.a.t.e.m.a.t.i.i.k.a.n_t.u.k.i.o.p.e.t.u.s",0,"fi","NORDIC","curated","high","neutral_obfuscated"
"M.u.u.t.t.o.s.i.i.v.o.u.s_a.m.m.a.t.t.i.t.a.i.d.o.l.l.a",0,"fi","NORDIC","curated","high","neutral_obfuscated"\n""",
    },
    "v7.2_sexual": {
        "SE": """"text","label","language","country_group","source","confidence_hint","notes"
"Snabba pengar utan avtal och dokument, skriv till PM",1,"sv","NORDIC","curated","high","financial_fraud"
"Diskret möte i centrum, endast kontanter, DM för info",1,"sv","NORDIC","curated","high","illegal_services"
"Arbeta hemifrån, tjäna 5000 kr om dagen utan erfarenhet",1,"sv","NORDIC","curated","high","recruitment_scam"
"Betala i kryptovaluta för snabb leverans utan spårning",1,"sv","NORDIC","curated","high","black_market"
"Söker privat arrangemang, kontant betalning i natt",1,"sv","NORDIC","curated","high","transactional_solicitation"
"Låna pengar snabbt utan kreditupplysning och inkomstkrav",1,"sv","NORDIC","curated","high","financial_fraud"
"Säljer receptbelagda mediciner billigt och diskret",1,"sv","NORDIC","curated","high","illegal_goods"
"Exklusivt sällskap för vuxna, ring för priser och boka",1,"sv","NORDIC","curated","high","illegal_services"
"Investera 1000 kr och få 10000 kr tillbaka på en vecka",1,"sv","NORDIC","curated","high","financial_scam"
"Säljer pass och id-kort helt äkta kvalitet",1,"sv","NORDIC","curated","high","illegal_goods"
"Tjäna lätta pengar som kurir, inga frågor ställs",1,"sv","NORDIC","curated","high","recruitment_scam"
"Söker ung tjej för finansiellt samarbete i Göteborg",1,"sv","NORDIC","curated","high","transactional_solicitation"
"Köper allt stöldgods, snabba kontanter i handen",1,"sv","NORDIC","curated","high","black_market"
"Snabb utbetalning utan avtal, skriv direkt på WhatsApp",1,"sv","NORDIC","curated","high","financial_fraud"
"Diskret massage och avkoppling i privat lägenhet",1,"sv","NORDIC","curated","high","illegal_services"
"Snabblån utan säkerhet utbetalas inom 15 minuter",1,"sv","NORDIC","curated","high","financial_fraud"
"Säljer falska körkort och dokument snabbt",1,"sv","NORDIC","curated","high","illegal_goods"
"Söker kvinna för diskreta möten mot ersättning",1,"sv","NORDIC","curated","high","transactional_solicitation"
"Köp narkotika säkert och anonymt på nätet",1,"sv","NORDIC","curated","high","black_market"
"Snabba cash utan deklaration, kontakta oss direkt",1,"sv","NORDIC","curated","high","financial_fraud"
"Ansök om privatlån via officiell bank med låg ränta",0,"sv","NORDIC","curated","high","legit_finance"
"Söker arbete som snickare, har 5 års erfarenhet och referenser",0,"sv","NORDIC","curated","high","legit_employment"
"Vi erbjuder professionell rådgivning om skatt och ekonomi",0,"sv","NORDIC","curated","high","legit_business"
"Begagnad soffa säljes på grund av flytt, hämtas i Malmö",0,"sv","NORDIC","curated","high","neutral_listing"
"Möbelmontering utföres noggrant av behörig hantverkare",0,"sv","NORDIC","curated","high","legit_services"
"Säljer min bil, full servicebok och nyligen besiktigad",0,"sv","NORDIC","curated","high","neutral_listing"
"Lediga tjänster som undersköterska på äldreboende i Stockholm",0,"sv","NORDIC","curated","high","legit_employment"
"Söker hyresgäst till möblerad etta från och med nästa månad",0,"sv","NORDIC","curated","high","neutral_listing"
"Erbjuder läxhjälp i matematik för gymnasieelever",0,"sv","NORDIC","curated","high","legit_services"
"Auktoriserad redovisningskonsult hjälper med ditt bokslut",0,"sv","NORDIC","curated","high","legit_business"
"Professionell flyttstädning med nöjd-kund-garanti",0,"sv","NORDIC","curated","high","legit_services"
"Önskar köpa cykel i god kondition för daglig pendling",0,"sv","NORDIC","curated","high","neutral_listing"
"Restaurang söker erfaren kock för helgtjänstgöring",0,"sv","NORDIC","curated","high","legit_employment"
"Hundpassning erbjudes i lugn och trygg hemmamiljö",0,"sv","NORDIC","curated","high","legit_services"
"Säljer begagnad bärbar dator i mycket gott skick",0,"sv","NORDIC","curated","high","neutral_listing"
"Officiell bilverkstad utför service på alla bilmärken",0,"sv","NORDIC","curated","high","legit_services"
"Fastighetsbolag hyr ut kontorslokaler i centrala Malmö",0,"sv","NORDIC","curated","high","legit_business"
"Söker barnvakt två kvällar i veckan i Uppsala",0,"sv","NORDIC","curated","high","legit_employment"
"Erbjuder sånglektioner för nybörjare och avancerade",0,"sv","NORDIC","curated","high","legit_services"
"Säljer matbord med sex stolar i gott skick",0,"sv","NORDIC","curated","high","neutral_listing"\n""",
        "DK": """"text","label","language","country_group","source","confidence_hint","notes"
"Hurtige penge uden kontrakt og dokumenter, skriv i DM",1,"da","NORDIC","curated","high","financial_fraud"
"Diskret møde i centrum, kun kontanter, DM for info",1,"da","NORDIC","curated","high","illegal_services"
"Arbejd hjemmefra, tjen 5000 kr om dagen uden erfaring",1,"da","NORDIC","curated","high","recruitment_scam"
"Hurtigt lån uden kredittjek og sikkerhed, skriv hurtigt",1,"da","NORDIC","curated","high","financial_fraud"
"Privat aftale tilbydes, kun kontant afregning i aften",1,"da","NORDIC","curated","high","transactional_solicitation"
"Lån penge på minuttet uden indkomstbevis, kontakt os",1,"da","NORDIC","curated","high","financial_fraud"
"Sælger receptpligtig medicin billigt og diskret",1,"da","NORDIC","curated","high","illegal_goods"
"Eskort og diskret selskab i København, ring for info",1,"da","NORDIC","curated","high","illegal_services"
"Invester 1000 kr og få ti tusinde tilbage på få dage",1,"da","NORDIC","curated","high","financial_scam"
"Sælger ægte pas og kørekort i høj kvalitet",1,"da","NORDIC","curated","high","illegal_goods"
"Tjen hurtige penge som kurer, ingen spørgsmål stilles",1,"da","NORDIC","curated","high","recruitment_scam"
"Søger ung pige til økonomisk aftale i Aarhus",1,"da","NORDIC","curated","high","transactional_solicitation"
"Køber alt fra tyveri, kontant afregning med det samme",1,"da","NORDIC","curated","high","black_market"
"Hurtig udbetaling uden papirer, skriv på WhatsApp",1,"da","NORDIC","curated","high","financial_fraud"
"Diskret kropsmassage i privat lejlighed i centrum",1,"da","NORDIC","curated","high","illegal_services"
"Hurtiglån uden RKI registrering og uden sikkerhed",1,"da","NORDIC","curated","high","financial_fraud"
"Sælger falske dokumenter og ID kort hurtigt",1,"da","NORDIC","curated","high","illegal_goods"
"Søger kvinde til diskrete aftaler mod betaling",1,"da","NORDIC","curated","high","transactional_solicitation"
"Køb euforiserende stoffer sikkert på nettet",1,"da","NORDIC","curated","high","black_market"
"Hurtige kontanter uden skat, skriv til os nu",1,"da","NORDIC","curated","high","financial_fraud"
"Vi tilbyder professionel rådgivning om skat og økonomi",0,"da","NORDIC","curated","high","legit_business"
"Søger job som tømrer, har 5 års erfaring og referencer",0,"da","NORDIC","curated","high","legit_employment"
"Ansøg om privatlån via officiel bank med lav rente",0,"da","NORDIC","curated","high","legit_finance"
"Brugt spisebord til salg på grund af flytning i København",0,"da","NORDIC","curated","high","neutral_listing"
"Rengøring af kontorer udføres af professionelt firma",0,"da","NORDIC","curated","high","legit_services"
"Sælger velholdt bil nysynet og med fuld servicebog",0,"da","NORDIC","curated","high","neutral_listing"
"Søger sygeplejerske til fast stilling på hospitalet",0,"da","NORDIC","curated","high","legit_employment"
"Lejlighed fremlejes møbleret fra næste måned i Odense",0,"da","NORDIC","curated","high","neutral_listing"
"Eksamensforberedelse og lektiehjælp i engelsk tilbydes",0,"da","NORDIC","curated","high","legit_services"
"Statsautoriseret revisor hjælper med dit årsregnskab",0,"da","NORDIC","curated","high","legit_business"
"Grundig flytterengøring med kvalitetssikring og garanti",0,"da","NORDIC","curated","high","legit_services"
"Ønsker at købe en god brugt herrecykel",0,"da","NORDIC","curated","high","neutral_listing"
"Café søger smilende tjener til deltidsstilling",0,"da","NORDIC","curated","high","legit_employment"
"Erfaren hundepasser tilbyder pasning i private rammer",0,"da","NORDIC","curated","high","legit_services"
"Sælger brugt bærbar computer i god stand",0,"da","NORDIC","curated","high","neutral_listing"
"Godkendt bilværksted udfører reparationer på alle mærker",0,"da","NORDIC","curated","high","legit_services"
"Erhvervsejendom udlejer kontorlokaler i centralt Aarhus",0,"da","NORDIC","curated","high","legit_business"
"Søger babysitter to aftener om ugen i Aalborg",0,"da","NORDIC","curated","high","legit_employment"
"Privat musikundervisning i klaver for begyndere",0,"da","NORDIC","curated","high","legit_services"
"Sælger spisebord med seks stole i rigtig god stand",0,"da","NORDIC","curated","high","neutral_listing"\n""",
        "NO": """"text","label","language","country_group","source","confidence_hint","notes"
"Raske penger uten kontrakt og dokumenter, skriv til PM",1,"no","NORDIC","curated","high","financial_fraud"
"Diskré møte i sentrum, kun kontanter, DM for info",1,"no","NORDIC","curated","high","illegal_services"
"Jobb hjemmefra, tjen 5000 kr om dagen uten erfaring",1,"no","NORDIC","curated","high","recruitment_scam"
"Lån penger på dagen uten sjekk av inntekt, ta kontakt",1,"no","NORDIC","curated","high","financial_fraud"
"Søker privat avtale, kontant betaling i kveld",1,"no","NORDIC","curated","high","transactional_solicitation"
"Kreditt uten kredittsjekk og papirer, skriv direkte",1,"no","NORDIC","curated","high","financial_fraud"
"Selger reseptbelagte medisiner billig og diskré",1,"no","NORDIC","curated","high","illegal_goods"
"Diskré selskap for voksne menn i Oslo, ring for pris",1,"no","NORDIC","curated","high","illegal_services"
"Invester tusen kroner og få tidobbelt tilbake på ei uke",1,"no","NORDIC","curated","high","financial_scam"
"Selger ekte pass og førerkort av høy kvalitet",1,"no","NORDIC","curated","high","illegal_goods"
"Tjen raske penger som kurer, ingen spørsmål stilt",1,"no","NORDIC","curated","high","recruitment_scam"
"Søker ung jente for økonomisk samarbeid i Bergen",1,"no","NORDIC","curated","high","transactional_solicitation"
"Kjøper tjuvgods mot umiddelbar kontant betaling",1,"no","NORDIC","curated","high","black_market"
"Rask utbetaling uten papirer, ta kontakt på WhatsApp",1,"no","NORDIC","curated","high","financial_fraud"
"Diskré massasje og avkobling i privat leilighet",1,"no","NORDIC","curated","high","illegal_services"
"Hurtiglån uten kredittsjekk og uten sikkerhet på minuttet",1,"no","NORDIC","curated","high","financial_fraud"
"Selger falske førerkort og ID papirer raskt",1,"no","NORDIC","curated","high","illegal_goods"
"Søker kvinne for diskré møter mot god betaling",1,"no","NORDIC","curated","high","transactional_solicitation"
"Kjøp ulovlige stoffer trygt og anonymt på nett",1,"no","NORDIC","curated","high","black_market"
"Raske kontanter uten skattemelding, ta kontakt nå",1,"no","NORDIC","curated","high","financial_fraud"
"Vi tilbyr profesjonell rådgivning om skatt og økonomi",0,"no","NORDIC","curated","high","legit_business"
"Søker jobb som tømrer, har 5 års erfaring og referanser",0,"no","NORDIC","curated","high","legit_employment"
"Søk om forbrukslån via godkjent bank med lav rente",0,"no","NORDIC","curated","high","legit_finance"
"Brukt sofa selges rimelig på grunn av flytting i Oslo",0,"no","NORDIC","curated","high","neutral_listing"
"Maling og oppussing utføres av erfaren håndverker",0,"no","NORDIC","curated","high","legit_services"
"Selger pent brukt bil nylig EU-godkjent og servet",0,"no","NORDIC","curated","high","neutral_listing"
"Søker sykepleier til fast stilling ved sykehjemmet",0,"no","NORDIC","curated","high","legit_employment"
"Møblert leilighet til leie fra og med neste måned",0,"no","NORDIC","curated","high","neutral_listing"
"Tilbyr leksehjelp i realfag for ungdomsskoleelever",0,"no","NORDIC","curated","high","legit_services"
"Autorisert regnskapsfører hjelper med årsoppgjøret",0,"no","NORDIC","curated","high","legit_business"
"Profesjonell flyttevask med garanti for godkjent overlevering",0,"no","NORDIC","curated","high","legit_services"
"Ønsker å kjøpe en god tursykkel i god stand",0,"no","NORDIC","curated","high","neutral_listing"
"Restaurant søker dyktig servitør for helgejobb",0,"no","NORDIC","curated","high","legit_employment"
"Tilbyr hundepass i rolige omgivelser nær marka",0,"no","NORDIC","curated","high","legit_services"
"Selger pent brukt bærbar PC i god stand",0,"no","NORDIC","curated","high","neutral_listing"
"Godkjent bilverksted utfører service på alle merker",0,"no","NORDIC","curated","high","legit_services"
"Eiendomsselskap leier ut kontorlokaler i sentrum av Bergen",0,"no","NORDIC","curated","high","legit_business"
"Søker barnevakt to kvelder i uken i Trondheim",0,"no","NORDIC","curated","high","legit_employment"
"Erbjuder gitarrtimer for nybegynnere og viderekomne",0,"no","NORDIC","curated","high","legit_services"
"Selger spisebord med seks stoler i god stand",0,"no","NORDIC","curated","high","neutral_listing"\n""",
        "FI": """"text","label","language","country_group","source","confidence_hint","notes"
"Nopeaa rahaa ilman sopimusta ja asiakirjoja, kirjoita YV",1,"fi","NORDIC","curated","high","financial_fraud"
"Harkitsetko helppoa rahaa, ei verotusta, ota yhteyttä",1,"fi","NORDIC","curated","high","financial_fraud"
"Hienotunteinen tapaaminen keskustassa, vain käteinen",1,"fi","NORDIC","curated","high","illegal_services"
"Tienaa 500 euroa päivässä kotoa käsin ilman kokemusta",1,"fi","NORDIC","curated","high","recruitment_scam"
"Etsitään yksityistä järjestelyä, maksu käteisellä heti",1,"fi","NORDIC","curated","high","transactional_solicitation"
"Lainaa rahaa heti ilman luottotietojen tarkistusta",1,"fi","NORDIC","curated","high","financial_fraud"
"Myydään reseptilääkkeitä edullisesti ja diskreetisti",1,"fi","NORDIC","curated","high","illegal_goods"
"Yksityistä seuraa aikuisille Helsingissä, soita ja varaa",1,"fi","NORDIC","curated","high","illegal_services"
"Sijoita satanen ja saa tuhat euroa takaisin viikossa",1,"fi","NORDIC","curated","high","financial_scam"
"Myydään aitoja passeja ja ajokortteja laadukkaasti",1,"fi","NORDIC","curated","high","illegal_goods"
"Tienaa helppoa rahaa kuriirina, ei kysymyksiä",1,"fi","NORDIC","curated","high","recruitment_scam"
"Etsitään nuorta naista taloudelliseen yhteistyöhön Tampereella",1,"fi","NORDIC","curated","high","transactional_solicitation"
"Ostetaan varastettua tavaraa, käteismaksu heti käteen",1,"fi","NORDIC","curated","high","black_market"
"Nopea maksu ilman papereita, ota yhteyttä WhatsAppissa",1,"fi","NORDIC","curated","high","financial_fraud"
"Hienotunteista hierontaa ja rentoutumista yksityisasunnossa",1,"fi","NORDIC","curated","high","illegal_services"
"Pikalainaa heti tilille ilman luottotietoja ja vakuuksia",1,"fi","NORDIC","curated","high","financial_fraud"
"Myydään väärennettyjä henkilökortteja ja passeja",1,"fi","NORDIC","curated","high","illegal_goods"
"Etsitään naista hienotunteisiin tapaamisiin korvausta vastaan",1,"fi","NORDIC","curated","high","transactional_solicitation"
"Osta laittomia tuotteita turvallisesti verkon kautta",1,"fi","NORDIC","curated","high","black_market"
"Nopeaa käteistä ilman verotusta, ota yhteyttä heti",1,"fi","NORDIC","curated","high","financial_fraud"
"Hae yksityislainaa virallisen pankin kautta myönteisin ehdoin",0,"fi","NORDIC","curated","high","legit_finance"
"Etsin työtä puuseppänä, 5 vuoden kokemus ja suositukset",0,"fi","NORDIC","curated","high","legit_employment"
"Tarjoamme asiantuntevaa veroneuvontaa ja kirjanpitoa",0,"fi","NORDIC","curated","high","legit_business"
"Myydään hyväkuntoinen kulmasohva muuton vuoksi Oulussa",0,"fi","NORDIC","curated","high","neutral_listing"
"Kotisiivous ammattitaidolla ja luotettavasti Tampereella",0,"fi","NORDIC","curated","high","legit_services"
"Myydään siisti ja katsastettu henkilöauto täydellä huoltokirjalla",0,"fi","NORDIC","curated","high","neutral_listing"
"Haetaan lähihoitajaa vakituiseen työsuhteeseen Espoossa",0,"fi","NORDIC","curated","high","legit_employment"
"Vuokrataan kalustettu yksiö ensi kuun alusta alkaen",0,"fi","NORDIC","curated","high","neutral_listing"
"Tarjotaan matematiikan tukiopetusta lukiolaisille",0,"fi","NORDIC","curated","high","legit_services"
"Kulttuurialan yritys hakee kokenutta kirjanpitäjää",0,"fi","NORDIC","curated","high","legit_business"
"Ammattimainen muuttosiivous takuulla ja kuitilla",0,"fi","NORDIC","curated","high","legit_services"
"Ostetaan hyväkuntoinen miesten polkupyörä",0,"fi","NORDIC","curated","high","neutral_listing"
"Ravintola hakee reipasta tarjoilijaa viikonloppuvuoroihin",0,"fi","NORDIC","curated","high","legit_employment"
"Kokenut koiranhoitaja tarjoaa hoitopaikkaa kotonaan",0,"fi","NORDIC","curated","high","legit_services"
"Myydään vähän käytetty kannettava tietokone",0,"fi","NORDIC","curated","high","neutral_listing"
"Valtuutettu autohuolto suorittaa korjaukset kaikille merkeille",0,"fi","NORDIC","curated","high","legit_services"
"Kiinteistöyhtiö vuokraa toimistotilaa Turun keskustasta",0,"fi","NORDIC","curated","high","legit_business"
"Etsitään lapsenvahtia kahtena iltana viikossa Vantaalla",0,"fi","NORDIC","curated","high","legit_employment"
"Yksityistä pianonsoiton opetusta vasta-alkajille",0,"fi","NORDIC","curated","high","legit_services"
"Myydään ruokapöytä ja kuusi tuolia hyvässä kunnossa",0,"fi","NORDIC","curated","high","neutral_listing"\n""",
    }
}

PROCESSED_MAPPING = {
    "v7_sexual": "nordic_v7_base.csv",
    "v7.1_sexual": "nordic_v7_1_slang.csv",
    "v7.2_sexual": "nordic_v7_2_context.csv"
}

def build_nordic_datasets():
    """Атомарная сборка RAW слоев и их интеграция в PROCESSED."""
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    
    for model_version, country_files in DATASETS.items():
        model_dir = RAW_DIR / model_version / "NORDIC"
        model_dir.mkdir(parents=True, exist_ok=True)
        
        aggregated_dfs = []
        
        for lang_code, csv_content in country_files.items():
            file_path = model_dir / f"{lang_code}.csv"
            
            # Запись исходника в raw/
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(csv_content)
            
            df = pd.read_csv(file_path)
            aggregated_dfs.append(df)
            print(f"  └─ Generated RAW: {file_path.relative_to(BASE_DIR)} ({len(df)} rows)")
            
        # Объединение и сохранение в data/processed/
        combined_df = pd.concat(aggregated_dfs, ignore_index=True)
        processed_target = PROCESSED_DIR / PROCESSED_MAPPING[model_version]
        combined_df.to_csv(processed_target, index=False, encoding="utf-8")
        print(f"✅ Aggregated PROCESSED: {processed_target.relative_to(BASE_DIR)} (Total: {len(combined_df)} rows)\n")

if __name__ == "__main__":
    print("🚀 Running Automated NORDIC Dataset Generator...")
    build_nordic_datasets()
    print("🏁 Execution completed successfully.")