#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Expanded Data Generator & Aggregator for BALKAN Cluster (v8, v8.1, v8.2)
Author: Maksym Nenashev (Systems Engineer)
"""

import sys
from pathlib import Path
import pandas as pd

BASE_DIR = Path(__file__).resolve().parent.parent
RAW_DIR = BASE_DIR / "raw"
PROCESSED_DIR = BASE_DIR / "data" / "processed"

DATASETS = {
    "v8_sexual": {
        "HR": """"text","label","language","country_group","source","confidence_hint","notes"
"Ubit ću te ti jebeni idiote",1,"hr","BALKAN","curated","high","direct_threat"
"Znam gdje živiš pazi se noga",1,"hr","BALKAN","curated","high","stalking_threat"
"Možeš li mi poslati golišave slike",1,"hr","BALKAN","curated","high","explicit_request"
"Ti si jebena pička i svinja",1,"hr","BALKAN","curated","high","overt_insult"
"Pretući ću te jebemu mater",1,"hr","BALKAN","curated","high","direct_threat"
"Nudiš li seksualne usluge za novac",1,"hr","BALKAN","curated","high","transactional_solicitation"
"Želim te vidjeti golu odmah",1,"hr","BALKAN","curated","high","explicit_request"
"Pronaći ću tvoju obitelj i naškoditi vam",1,"hr","BALKAN","curated","high","stalking_threat"
"Jebi se ti jebeni idiote",1,"hr","BALKAN","curated","high","overt_insult"
"Čekam te ispred kuće izađi vani",1,"hr","BALKAN","curated","high","stalking_threat"
"Polomit ću ti sve kosti",1,"hr","BALKAN","curated","high","direct_threat"
"Pošalji svoje privatne slike odmah",1,"hr","BALKAN","curated","high","explicit_request"
"Uništit ću ti život potpuno",1,"hr","BALKAN","curated","high","direct_threat"
"Popuši mi kurac ti jebena droljo",1,"hr","BALKAN","curated","high","overt_insult"
"Zažalit ćeš što si se rodio",1,"hr","BALKAN","curated","high","direct_threat"
"Mrtav si čim te vidim na ulici",1,"hr","BALKAN","curated","high","direct_threat"
"Daj mi svoje nude fotke ili ću te raširiti",1,"hr","BALKAN","curated","high","explicit_request"
"Zaklat ću te kao psa",1,"hr","BALKAN","curated","high","direct_threat"
"Smeće jedno pokvareno gubi se",1,"hr","BALKAN","curated","high","overt_insult"
"Nijedan policajac te neće spasiti od mene",1,"hr","BALKAN","curated","high","direct_threat"
"Prodajem rabljeni bicikl u dobrom stanju",0,"hr","BALKAN","curated","high","neutral_listing"
"Hvala na brzom odgovoru i odličnoj usluzi",0,"hr","BALKAN","curated","high","neutral_communication"
"Možemo li zakazati sastanak sutra u 10 sati",0,"hr","BALKAN","curated","high","neutral_business"
"Želim kupiti drveni blagovaonski stol",0,"hr","BALKAN","curated","high","neutral_listing"
"Pozdrav želim postaviti pitanje o vašoj usluzi",0,"hr","BALKAN","curated","high","neutral_query"
"Tražim stan za najam u Zagrebu",0,"hr","BALKAN","curated","high","neutral_listing"
"Možete li poslati račun na moju e-mail adresu",0,"hr","BALKAN","curated","high","neutral_business"
"Knjiga je bila vrlo zanimljiva i korisna",0,"hr","BALKAN","curated","high","neutral_communication"
"Prodajem dječju odjeću veličine 92 novo",0,"hr","BALKAN","curated","high","neutral_listing"
"Koje je radno vrijeme vaše korisničke službe",0,"hr","BALKAN","curated","high","neutral_query"
"Nudimo termine za zdravstveni pregled u klinici",0,"hr","BALKAN","curated","high","legit_services"
"Želio bih naručiti dvije ulaznice za kazalište",0,"hr","BALKAN","curated","high","neutral_business"
"Psu je potrebna šetnja svakog poslijepodneva",0,"hr","BALKAN","curated","high","neutral_communication"
"Tečaj počinje sljedećeg ponedjeljka u devet sati",0,"hr","BALKAN","curated","high","neutral_business"
"Bilo je zadovoljstvo upoznati vas na konferenciji",0,"hr","BALKAN","curated","high","neutral_communication"
"Službeni autoservis vrši popravke svih marki",0,"hr","BALKAN","curated","high","legit_services"
"Iznajmljujemo uredski prostor u centru grada",0,"hr","BALKAN","curated","high","legit_business"
"Tražimo dadilju za dvoje djece dvaput tjedno",0,"hr","BALKAN","curated","high","legit_employment"
"Nudimo poduke iz matematike za srednjoškolce",0,"hr","BALKAN","curated","high","legit_services"
"Prodajem radni stol u vrlo dobrom stanju",0,"hr","BALKAN","curated","high","neutral_listing"\n""",
        "BG": """"text","label","language","country_group","source","confidence_hint","notes"
"Ще те убия ти шибан идиот",1,"bg","BALKAN","curated","high","direct_threat"
"Знам къде живееш внимавай много",1,"bg","BALKAN","curated","high","stalking_threat"
"Можеш ли да ми изпратиш голи снимки",1,"bg","BALKAN","curated","high","explicit_request"
"Ти си шибана путка и прасе",1,"bg","BALKAN","curated","high","overt_insult"
"Ще те пребия куче такова",1,"bg","BALKAN","curated","high","direct_threat"
"Предлагаш ли сексуални услуги срещу заплащане",1,"bg","BALKAN","curated","high","transactional_solicitation"
"Искам да те видя гола веднага",1,"bg","BALKAN","curated","high","explicit_request"
"Ще намеря семейството ти и ще ви нараня",1,"bg","BALKAN","curated","high","stalking_threat"
"Млъкни ти шибан идиот",1,"bg","BALKAN","curated","high","overt_insult"
"Чакам те пред къщата ти излез навън",1,"bg","BALKAN","curated","high","stalking_threat"
"Ще ти счупя всички кости",1,"bg","BALKAN","curated","high","direct_threat"
"Изпрати личните си снимки веднага",1,"bg","BALKAN","curated","high","explicit_request"
"Ще съсипя живота ти напълно",1,"bg","BALKAN","curated","high","direct_threat"
"Лапай пишката ми шибана курво",1,"bg","BALKAN","curated","high","overt_insult"
"Ще съжаляваш че си се родил",1,"bg","BALKAN","curated","high","direct_threat"
"Мъртъв си щом те видя на улицата",1,"bg","BALKAN","curated","high","direct_threat"
"Прати голи снимки или ще разпространя всичко",1,"bg","BALKAN","curated","high","explicit_request"
"Ще те заколя като куче",1,"bg","BALKAN","curated","high","direct_threat"
"Боклук такъв разкарай се оттук",1,"bg","BALKAN","curated","high","overt_insult"
"Никой полицай няма да те спаси от мен",1,"bg","BALKAN","curated","high","direct_threat"
"Продавам употребяван велосипед в добро състояние",0,"bg","BALKAN","curated","high","neutral_listing"
"Благодаря за бързия отговор и отличното обслужване",0,"bg","BALKAN","curated","high","neutral_communication"
"Може ли да насрочим среща утре в 10 часа",0,"bg","BALKAN","curated","high","neutral_business"
"Купувам дървена трапезна маса",0,"bg","BALKAN","curated","high","neutral_listing"
"Здравейте искам да попитам за вашата услуга",0,"bg","BALKAN","curated","high","neutral_query"
"Търся апартамент под наем в София",0,"bg","BALKAN","curated","high","neutral_listing"
"Може ли да изпратите фактурата на имейла ми",0,"bg","BALKAN","curated","high","neutral_business"
"Книгата беше много интересна и полезна",0,"bg","BALKAN","curated","high","neutral_communication"
"Продавам детски дрехи размер 92 чисто нови",0,"bg","BALKAN","curated","high","neutral_listing"
"Какво е работното време на поддръжката",0,"bg","BALKAN","curated","high","neutral_query"
"Предлагаме час за медицински преглед в клиниката",0,"bg","BALKAN","curated","high","legit_services"
"Бих искал да поръчам два билета за театър",0,"bg","BALKAN","curated","high","neutral_business"
"Кучето има нужда от разходка всеки следобед",0,"bg","BALKAN","curated","high","neutral_communication"
"Курсът започва следващия понеделник в девет часа",0,"bg","BALKAN","curated","high","neutral_business"
"Беше ми приятно да се запознаем на конференцията",0,"bg","BALKAN","curated","high","neutral_communication"
"Официален автосервиз извършва ремонти на всички марки",0,"bg","BALKAN","curated","high","legit_services"
"Отдаваме под наем офиси в центъра на града",0,"bg","BALKAN","curated","high","legit_business"
"Търсим бавачка за две деца два пъти седмично",0,"bg","BALKAN","curated","high","legit_employment"
"Предлагаме уроци по математика за ученици",0,"bg","BALKAN","curated","high","legit_services"
"Продавам бюро в много добро състояние",0,"bg","BALKAN","curated","high","neutral_listing"\n""",
        "SL": """"text","label","language","country_group","source","confidence_hint","notes"
"Ubil te bom ti jebeni idiot",1,"sl","BALKAN","curated","high","direct_threat"
"Vem kje živiš pazi se dobro",1,"sl","BALKAN","curated","high","stalking_threat"
"Mi lahko pošlješ golišave slike zdaj",1,"sl","BALKAN","curated","high","explicit_request"
"Ti si jebena pička in prašič",1,"sl","BALKAN","curated","high","overt_insult"
"Pretepel te bom ti mrha",1,"sl","BALKAN","curated","high","direct_threat"
"Ali ponujaš spolne storitve za denar",1,"sl","BALKAN","curated","high","transactional_solicitation"
"Želim te videti golo takoj zdaj",1,"sl","BALKAN","curated","high","explicit_request"
"Našel bom tvojo družino in vas poškodoval",1,"sl","BALKAN","curated","high","stalking_threat"
"Zapri usta ti jebeni idiot",1,"sl","BALKAN","curated","high","overt_insult"
"Čakam te pred hišo pridi ven",1,"sl","BALKAN","curated","high","stalking_threat"
"Polomil ti bom vse kosti",1,"sl","BALKAN","curated","high","direct_threat"
"Pošlji svoje zasebne slike takoj",1,"sl","BALKAN","curated","high","explicit_request"
"Uničil ti bom življenje popolnoma",1,"sl","BALKAN","curated","high","direct_threat"
"Moli moj kurac ti jebena kurba",1,"sl","BALKAN","curated","high","overt_insult"
"Obžaloval boš da si se rodil",1,"sl","BALKAN","curated","high","direct_threat"
"Mrtev si takoj ko te vidim na ulici",1,"sl","BALKAN","curated","high","direct_threat"
"Daj mi golišave fotke ali te razkrijem",1,"sl","BALKAN","curated","high","explicit_request"
"Zaklal te bom kot psa",1,"sl","BALKAN","curated","high","direct_threat"
"Smeti eno pokvarjeno poberi se",1,"sl","BALKAN","curated","high","overt_insult"
"Noben policist te ne bo rešil pred mano",1,"sl","BALKAN","curated","high","direct_threat"
"Prodam rabljeno kolo v dobrem stanju",0,"sl","BALKAN","curated","high","neutral_listing"
"Hvala za hiter odgovor in odlično storitev",0,"sl","BALKAN","curated","high","neutral_communication"
"Ali lahko rezerviramo sestanek jutri ob 10h",0,"sl","BALKAN","curated","high","neutral_business"
"Kupim leseno jedilno mizo",0,"sl","BALKAN","curated","high","neutral_listing"
"Pozdravljeni rad bi vprašal o vaši storitvi",0,"sl","BALKAN","curated","high","neutral_query"
"Iščem stanovanje za najem v Ljubljani",0,"sl","BALKAN","curated","high","neutral_listing"
"Ali lahko pošljete račun na moj e-poštni naslov",0,"sl","BALKAN","curated","high","neutral_business"
"Knjiga je bila zelo zanimiva in poučna",0,"sl","BALKAN","curated","high","neutral_communication"
"Prodam otroška oblačila velikosti 92 novo",0,"sl","BALKAN","curated","high","neutral_listing"
"Kakšen je delovni čas podpore strankam",0,"sl","BALKAN","curated","high","neutral_query"
"Nudimo termine za zdravstveni pregled v kliniki",0,"sl","BALKAN","curated","high","legit_services"
"Rada bi naročila dve vstopnici za gledališče",0,"sl","BALKAN","curated","high","neutral_business"
"Pes rabi sprehod vsako popoldne",0,"sl","BALKAN","curated","high","neutral_communication"
"Tečaj se začne naslednji ponedeljek ob devetih",0,"sl","BALKAN","curated","high","neutral_business"
"Lepo vas je bilo spoznati na konferenci",0,"sl","BALKAN","curated","high","neutral_communication"
"Uradni avtoservis opravlja popravila vseh znamk",0,"sl","BALKAN","curated","high","legit_services"
"Oddajamo pisarniške prostore v centru mesta",0,"sl","BALKAN","curated","high","legit_business"
"Iščemo varuško za dva otroka dvakrat na teden",0,"sl","BALKAN","curated","high","legit_employment"
"Nudimo inštrukcije matematike za srednješolce",0,"sl","BALKAN","curated","high","legit_services"
"Prodam pisalno mizo v zelo dobrem stanju",0,"sl","BALKAN","curated","high","neutral_listing"\n""",
        "SQ": """"text","label","language","country_group","source","confidence_hint","notes"
"Do të të vras o idiot i fëledhur",1,"sq","BALKAN","curated","high","direct_threat"
"E di ku banon ruaju mirë",1,"sq","BALKAN","curated","high","stalking_threat"
"Më dërgo foto lakuriq tani",1,"sq","BALKAN","curated","high","explicit_request"
"Je një kuçkë e fëledhur dhe derr",1,"sq","BALKAN","curated","high","overt_insult"
"Do të të rrah o bastard",1,"sq","BALKAN","curated","high","direct_threat"
"A ofron shërbime seksuale me para",1,"sq","BALKAN","curated","high","transactional_solicitation"
"Dua të të shoh lakuriq tani",1,"sq","BALKAN","curated","high","explicit_request"
"Do të gjej familjen tënde dhe do t'ju lëndoj",1,"sq","BALKAN","curated","high","stalking_threat"
"Pusho o idiot i fëledhur",1,"sq","BALKAN","curated","high","overt_insult"
"Po të pres jashtë shtëpisë dil jashtë",1,"sq","BALKAN","curated","high","stalking_threat"
"Do të të thyej të gjitha eshtrat",1,"sq","BALKAN","curated","high","direct_threat"
"Dërgo fotot e tua private menjëherë",1,"sq","BALKAN","curated","high","explicit_request"
"Do ta shkatërroj jetën tënde plotësisht",1,"sq","BALKAN","curated","high","direct_threat"
"Më thith karin o lavire e fëledhur",1,"sq","BALKAN","curated","high","overt_insult"
"Do të pendohesh që ke lindur",1,"sq","BALKAN","curated","high","direct_threat"
"Je i vdekur sapo të të shoh në rrugë",1,"sq","BALKAN","curated","high","direct_threat"
"Më jep foto lakuriq ose do t'i shpërndaj",1,"sq","BALKAN","curated","high","explicit_request"
"Do të të pres si qen",1,"sq","BALKAN","curated","high","direct_threat"
"Plehra e fëledhur ik nga këtu",1,"sq","BALKAN","curated","high","overt_insult"
"Asnjë polic nuk do të të shpëtojë nga unë",1,"sq","BALKAN","curated","high","direct_threat"
"Shes një biçikletë të përdorur në gjendje të mirë",0,"sq","BALKAN","curated","high","neutral_listing"
"Faleminderit për përgjigjen e shpejtë dhe shërbimin",0,"sq","BALKAN","curated","high","neutral_communication"
"A mund të caktojmë një takim nesër në 10",0,"sq","BALKAN","curated","high","neutral_business"
"Dua të blej një tryezë ngrënie prej druri",0,"sq","BALKAN","curated","high","neutral_listing"
"Përshëndetje dua të bëj një pyetje për shërbimin",0,"sq","BALKAN","curated","high","neutral_query"
"Po kërkoj një banesë me qira në Tiranë",0,"sq","BALKAN","curated","high","neutral_listing"
"A mund ta dërgoni faturën në adresën time të emailit",0,"sq","BALKAN","curated","high","neutral_business"
"Libri était shumë interesant dhe i dobishëm",0,"sq","BALKAN","curated","high","neutral_communication"
"Shes rroba për fëmijë masa 92 të reja",0,"sq","BALKAN","curated","high","neutral_listing"
"Cilat janë oraret e shërbimit të klientit",0,"sq","BALKAN","curated","high","neutral_query"
"Ofrojmë takime për kontroll shëndetësor në klinikë",0,"sq","BALKAN","curated","high","legit_services"
"Dëshiroj të porosis dy bileta për teatër",0,"sq","BALKAN","curated","high","neutral_business"
"Qeni ka nevojë për një shëtitje çdo pasdite",0,"sq","BALKAN","curated","high","neutral_communication"
"Kursi fillon të hënën e ardhshme në orën nëntë",0,"sq","BALKAN","curated","high","neutral_business"
"Ishte kënaqësi t'ju takoja në konferencë",0,"sq","BALKAN","curated","high","neutral_communication"
"Servisi zyrtar i makinave bën riparime për të gjitha markat",0,"sq","BALKAN","curated","high","legit_services"
"Japim me qira zyra në qendër të qytetit",0,"sq","BALKAN","curated","high","legit_business"
"Kërkojmë një kujdestare për dy fëmijë dy herë në javë",0,"sq","BALKAN","curated","high","legit_employment"
"Ofrojmë kurse matematike për nxënësit e shkollave të mesme",0,"sq","BALKAN","curated","high","legit_services"
"Shes tryezë pune në gjendje shumë të mirë",0,"sq","BALKAN","curated","high","neutral_listing"\n""",
    },
    "v8.1_sexual": {
        "HR": """"text","label","language","country_group","source","confidence_hint","notes"
"j_e_b_e_n_i_i_d_i_o_t",1,"hr","BALKAN","curated","high","obfuscation_spaces"
"u.b.i.t.i_t.e_g.e.d.o",1,"hr","BALKAN","curated","high","obfuscation_dots"
"j4vl4 1d10t n4k3n",1,"hr","BALKAN","curated","high","leet_speak"
"p_i_c_k_a_m_a_t_e_r_i_n_a",1,"hr","BALKAN","curated","high","obfuscation_spaces"
"g.o.l.i.s.a.v.e_s.l.i.k.e",1,"hr","BALKAN","curated","high","obfuscation_dots"
"d_r_o_l_j_o_j_e_b_e_n_a",1,"hr","BALKAN","curated","high","obfuscation_spaces"
"u.n.i.s.t.i.t.i_t.e",1,"hr","BALKAN","curated","high","obfuscation_dots"
"p!ck4_j3b3n4",1,"hr","BALKAN","curated","high","leet_speak"
"z.a.k.l.a.t.i_t.e",1,"hr","BALKAN","curated","high","obfuscation_dots"
"s_m_e_c_e_j_e_b_e_n_o",1,"hr","BALKAN","curated","high","obfuscation_spaces"
"n_u_d_e_f_o_t_k_e",1,"hr","BALKAN","curated","high","obfuscation_spaces"
"p.o.l.o.m.i.t.i_k.o.s.t.i",1,"hr","BALKAN","curated","high","obfuscation_dots"
"p_o_p_u_s_i_k_u_r_a_c",1,"hr","BALKAN","curated","high","obfuscation_spaces"
"m_r_t_a_v_s_i",1,"hr","BALKAN","curated","high","obfuscation_spaces"
"s_v_i_n_j_o_j_e_b_e_n_a",1,"hr","BALKAN","curated","high","obfuscation_spaces"
"u_b_i_t_i_t_e_n_o_c_a_s",1,"hr","BALKAN","curated","high","obfuscation_spaces"
"p!ck4_u_b_i_j_e_m_t_e",1,"hr","BALKAN","curated","high","leet_speak"
"k_u_r_v_o_j_e_b_e_n_a",1,"hr","BALKAN","curated","high","obfuscation_spaces"
"g.o.l.e_s.l.i.k.e_n.u",1,"hr","BALKAN","curated","high","obfuscation_dots"
"z_a_j_e_b_a_t_t_e",1,"hr","BALKAN","curated","high","obfuscation_spaces"
"P.r.o.d.a.j.e.m_b.i.c.i.k.l_f.i.n.i",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"H.v.a.l.a_n.a_p.o.m.o.c.i",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"S.a.s.t.a.n.a.k_s.u.t.r.a_o.b_1.0",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"K.u.p.u.j.e.m_s.t.o.l",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"R.a.c.u.n_n.a_e.m.a.i.l",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"B.i.l me.t.e.r_z.a.k.a.z.a.t.i",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"K.n.j.i.g.a_z.a.n.i.m.l.j.i.v.a",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"D.j.e.c.j.a_o.d.j.e.c.a",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"K.o.r.i.s.n.i.c.k.a_s.l.u.z.b.a",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"P.r.e.g.l.e.d_u_k.l.i.n.i.c.i",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"K.a.z.a.l.i.s.t.e_u.l.a.z.n.i.c.e",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"A.u.t.o.s.e.r.v.i.s_p.o.p.r.a.v.a.k",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"U.r.e.d.s.k.i_p.r.o.s.t.o.r",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"D.a.d.i.l.j.a_z.a_d.j.e.c.u",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"M.a.t.e.m.a.t.i.k.a_p.o.d.u.k.e",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"R.a.d.n.i_s.t.o.l_p.r.o.d.a.j.a",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"S.t.a.n_z.a_n.a.j.a.m",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"K.u.p.n.j.a_a.u.t.a",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"U.s.l.u.g.a_p.r.e.v.o.d.a",0,"hr","BALKAN","curated","high","neutral_obfuscated"
"O.d.l.i.c.a.n_p.r.o.i.z.v.o.d",0,"hr","BALKAN","curated","high","neutral_obfuscated"\n""",
        "BG": """"text","label","language","country_group","source","confidence_hint","notes"
"ш_и_б_а_н_и_д_и_о_т",1,"bg","BALKAN","curated","high","obfuscation_spaces"
"щ.е.т.е.у.б.и.я",1,"bg","BALKAN","curated","high","obfuscation_dots"
"г_о_л_и_с_н_и_м_к_и",1,"bg","BALKAN","curated","high","obfuscation_spaces"
"п_у_т_к_а_ш_и_б_а_н_а",1,"bg","BALKAN","curated","high","obfuscation_spaces"
"п.р.е.б.и.я.т.е",1,"bg","BALKAN","curated","high","obfuscation_dots"
"к_у_р_в_о_ш_и_б_а_н_а",1,"bg","BALKAN","curated","high","obfuscation_spaces"
"с.ъ.с.и.п.я.т.е",1,"bg","BALKAN","curated","high","obfuscation_dots"
"п!шк4_ш!б4н4",1,"bg","BALKAN","curated","high","leet_speak"
"з.а.к.о.л.я.т.е",1,"bg","BALKAN","curated","high","obfuscation_dots"
"б_о_к_л_у_к_ш_и_б_а_н",1,"bg","BALKAN","curated","high","obfuscation_spaces"
"г_о_л_и_ф_о_т_о_с",1,"bg","BALKAN","curated","high","obfuscation_spaces"
"с.ч.у.п.я.к.о.с.т.и",1,"bg","BALKAN","curated","high","obfuscation_dots"
"л_а_п_а_й_п_и_ш_к_а",1,"bg","BALKAN","curated","high","obfuscation_spaces"
"м_ъ_р_т_ъ_в_с_и",1,"bg","BALKAN","curated","high","obfuscation_spaces"
"с_в_и_н_я_ш_и_б_а_н_а",1,"bg","BALKAN","curated","high","obfuscation_spaces"
"щ_е_т_е_у_б_и_я_д_н_е_с",1,"bg","BALKAN","curated","high","obfuscation_spaces"
"п!тк4_у_б_и_й_с_т_в_о",1,"bg","BALKAN","curated","high","leet_speak"
"к_у_р_в_о_у_б_и_й_с_т_в_о",1,"bg","BALKAN","curated","high","obfuscation_spaces"
"г.о.л.и_с.н.и.м.к.и_н.о.в.и",1,"bg","BALKAN","curated","high","obfuscation_dots"
"з_а_к_л_а_н_и_е",1,"bg","BALKAN","curated","high","obfuscation_spaces"
"П.р.о.д.а.в.а.м_в.е.л.о.с.и.п.е.д",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"Б.л.а.г.о.д.а.р.я_з.а_о.т.г.о.в.о.р.а",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"С.р.е.щ.а_у.т.р.е_в_1.0",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"К.у.п.у.в.а.м_м.а.с.а",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"Ф.а.к.т.у.р.а_н.а_и.м.е.й.л",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"К.н.и.г.а_и.н.т.е.р.е.с.н.а",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"Д.е.т.с.к.и_д.р.е.х.и",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"П.о.д.д.р.ъ.ж.к.а_ч.а.с.о.в.е",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"П.р.е.г.л.е.д_в_к.л.и.н.и.к.а.т.а",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"Б.и.л.е.т.и_з.а_т.е.а.т.ъ.р",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"А.в.т.о.с.е.р.в.и.з_р.е.м.о.н.т",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"О.ф.и.с_п.о.д_н.а.е.м",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"Б.а.в.а.ч.к.а_з.а_д.е.ц.а",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"У.р.о.ц.и_п.о_м.а.т.е.м.а.т.и.к.а",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"Б.ю.р.о_п.р.о.д.а.ж.б.а",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"А.п.а.р.т.а.м.е.н.т_н.а.е.м",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"К.у.п.у.в.а.н.е_н.а_к.о.л.а",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"П.р.е.в.о.д_у.с.л.у.г.а",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"О.т.л.и.ч.е.н_п.р.о.д.у.к.т",0,"bg","BALKAN","curated","high","neutral_obfuscated"
"П.о.р.ъ.ч.к.а_д.о.с.т.а.в.к.а",0,"bg","BALKAN","curated","high","neutral_obfuscated"\n""",
        "SL": """"text","label","language","country_group","source","confidence_hint","notes"
"j_e_b_e_n_i_i_d_i_o_t",1,"sl","BALKAN","curated","high","obfuscation_spaces"
"u.b.i.l_t.e_b.o.m",1,"sl","BALKAN","curated","high","obfuscation_dots"
"g_o_l_i_s_a_v_e_s_l_i_k_e",1,"sl","BALKAN","curated","high","obfuscation_spaces"
"p_r_a_s_i_c_j_e_b_e_n_i",1,"sl","BALKAN","curated","high","obfuscation_spaces"
"p.r.e.t.e.p.e.l_t.e",1,"sl","BALKAN","curated","high","obfuscation_dots"
"k_u_r_b_a_j_e_b_e_n_a",1,"sl","BALKAN","curated","high","obfuscation_spaces"
"u.n.i.c.i.l_t.e",1,"sl","BALKAN","curated","high","obfuscation_dots"
"p!ck4_j3b3n4",1,"sl","BALKAN","curated","high","leet_speak"
"z.a.k.l.a.l_t.e",1,"sl","BALKAN","curated","high","obfuscation_dots"
"s_m_e_t_i_j_e_b_e_n_e",1,"sl","BALKAN","curated","high","obfuscation_spaces"
"g_o_l_e_s_l_i_k_e",1,"sl","BALKAN","curated","high","obfuscation_spaces"
"p.o.l.o.m.i.l_k.o.s.t.i",1,"sl","BALKAN","curated","high","obfuscation_dots"
"m_o_l_i_k_u_r_a_c",1,"sl","BALKAN","curated","high","obfuscation_spaces"
"m_r_t_e_v_s_i",1,"sl","BALKAN","curated","high","obfuscation_spaces"
"p_r_a_s_i_c_j_e_b_e_n",1,"sl","BALKAN","curated","high","obfuscation_spaces"
"u_b_i_t_i_t_e_d_a_n_a_s",1,"sl","BALKAN","curated","high","obfuscation_spaces"
"p!ck4_u_b_i_j_a.m",1,"sl","BALKAN","curated","high","leet_speak"
"k_u_r_b_a_u_b_o.j",1,"sl","BALKAN","curated","high","obfuscation_spaces"
"g.o.l.e_s.l.i.k.e_t.a.k.o.j",1,"sl","BALKAN","curated","high","obfuscation_dots"
"z_a_k_o.l_p_s_a",1,"sl","BALKAN","curated","high","obfuscation_spaces"
"P.r.o.d.a.m_k.o.l.o_v_d.o.b.r.e.m",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"H.v.a.l.a_z.a_o.d.g.o.v.o.r",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"S.e.s.t.a.n.e.k_j.u.t.r.i",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"K.u.p.i.m_m.i.z.o",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"R.a.c.u.n_n.a_e.p.o.s.t.a",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"K.n.j.i.g.a_p.o.u.c.n.a",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"O.t.r.o.s.k.a_o.b.l.a.c.i.l.a",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"D.e.l.o.v.n.i_c.a.s_p.o.d.p.o.r.e",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"P.r.e.g.l.e.d_v_k.l.i.n.i.k.i",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"V.s.t.o.p.n.i.c.e_z.a_g.l.e.d.a.l.i.s.c.e",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"A.v.t.o.s.e.r.v.i.s_p.o.p.r.a.v.i.l.o",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"P.i.s.a.r.n.a_n.a.j.e.m",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"V.a.r.s.t.v.o_o.t.r.o.k",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"I.n.s.t.r.u.k.c.i.j.e_m.a.t.e.m.a.t.i.k.e",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"P.i.s.a.l.n.a_m.i.z.a_p.r.o.d.a.j.a",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"S.t.a.n_n.a.j.e.m_L.j.u.b.l.j.a.n.a",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"N.a.k.u.p_a.v.t.a",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"P.r.e.v.a me.n.j.e_s.t.o.r.i.t.e.v",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"O.d.l.i.c.e.n_i.z.d.e.l.e.k",0,"sl","BALKAN","curated","high","neutral_obfuscated"
"D.o.s.t.a.v.a_n.a me.s.t.o",0,"sl","BALKAN","curated","high","neutral_obfuscated"\n""",
        "SQ": """"text","label","language","country_group","source","confidence_hint","notes"
"i_d_i_o_t_i_f_e_l_e_d_h_u_r_h",1,"sq","BALKAN","curated","high","obfuscation_spaces"
"d.o_t.e_v.r.a.s",1,"sq","BALKAN","curated","high","obfuscation_dots"
"f_o_t_o_l_a_k_u_r_i_q",1,"sq","BALKAN","curated","high","obfuscation_spaces"
"k_u_c_k_e_e_f_e_l_e_d_h_u_r_h",1,"sq","BALKAN","curated","high","obfuscation_spaces"
"d.o_t.e_r.r.a.h",1,"sq","BALKAN","curated","high","obfuscation_dots"
"l_a_v_i_r_e_e_f_e_l_e_d_h_u_r_h",1,"sq","BALKAN","curated","high","obfuscation_spaces"
"s.h.k.a.t.e.r.r.o.j_j.e.t.e.n",1,"sq","BALKAN","curated","high","obfuscation_dots"
"f0t0_l4kur!q",1,"sq","BALKAN","curated","high","leet_speak"
"p.r.e.s_s.i_q.e.n",1,"sq","BALKAN","curated","high","obfuscation_dots"
"p_l_e_h_r_a_e_f_e_l_e_d_h_u_r_h",1,"sq","BALKAN","curated","high","obfuscation_spaces"
"f_o_t_o_p_r_i_v_a_t_e",1,"sq","BALKAN","curated","high","obfuscation_spaces"
"t.h.y.e.j_e.s.h.t.r.a.t",1,"sq","BALKAN","curated","high","obfuscation_dots"
"m_t_h_i_t_h_k_a_r_i_n",1,"sq","BALKAN","curated","high","obfuscation_spaces"
"i_v_d_e_k_u_r_j_e",1,"sq","BALKAN","curated","high","obfuscation_spaces"
"d_e_r_r_i_f_e_l_e_d_h_u_r_h",1,"sq","BALKAN","curated","high","obfuscation_spaces"
"d_o_t_e_v_r_a_s_s_o_t",1,"sq","BALKAN","curated","high","obfuscation_spaces"
"k!ck4_u_b_i_j_e_m",1,"sq","BALKAN","curated","high","leet_speak"
"l_a_v_i_r_e_m_b_y me",1,"sq","BALKAN","curated","high","obfuscation_spaces"
"f.o.t.o.l.a.k.u.r.i.q_n.y.t",1,"sq","BALKAN","curated","high","obfuscation_dots"
"p_r_e_s_s_i_d_e_r_r",1,"sq","BALKAN","curated","high","obfuscation_spaces"
"S.h.e.s_b.i.c.i.k.l.e.t.e",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"F.a.l.e.m.i.n.d.e.r.i.t_p.e.r_s.h.e.r.b.i.m.i.n",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"T.a.k.i.m_n.e.s.e.r",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"D.u.a_t.e_b.l.e.j_t.r.y.e.z.e",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"F.a.t.u.r.a_n.e_e.m.a.i.l",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"L.i.b.r.i_i_d.o.b.i.s.h.e.m",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"R.r.o.b.a_p.e.r_f.e.m.i.j.e",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"O.r.a.r.e.t_e_s.h.e.r.b.i.m.i.t",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"K.o.n.t.r.o.l.l_s.h.e me.n.d.e.t.e.s.o.r",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"B.i.l.e.t.a_p.e.r_t.e.a.t.e.r",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"S.e.r.v.i.s_m.a.k.i.n.a.s",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"Z.y me_m.e_q.i.r.a",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"K.u.j.d.e.s.t.a.r.e_p.e.r_f.e.m.i.j.e",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"K.u.r.s.e_m.a.t.e.m.a.t.i.k.e",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"T.r.y.e.z.e_p.u me.n.e",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"B.a.n.e.s.e_m.e_q.i.r.a",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"B me.l.e me_m.a.k.i.n.e",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"S.h.e.r.b.i me_p.e.r me.k me.i me.m.i",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"P.r.o.d.u.k.t_i_m.i me.r",0,"sq","BALKAN","curated","high","neutral_obfuscated"
"D.o me.r me.g.i_n me_a.d.r.e.s.e",0,"sq","BALKAN","curated","high","neutral_obfuscated"\n""",
    },
    "v8.2_sexual": {
        "HR": """"text","label","language","country_group","source","confidence_hint","notes"
"Brzi novac bez ugovora i dokumenata javite se u DM",1,"hr","BALKAN","curated","high","financial_fraud"
"Diskretan susret u centru samo gotovina pišite za info",1,"hr","BALKAN","curated","high","illegal_services"
"Rad od kuće zaradite 500 eura dnevno bez iskustva",1,"hr","BALKAN","curated","high","recruitment_scam"
"Brzi zajam bez kreditne provjere i papira odmah",1,"hr","BALKAN","curated","high","financial_fraud"
"Tražim diskretno druženje uz novčanu naknadu večeras",1,"hr","BALKAN","curated","high","transactional_solicitation"
"Brzi pozajmica bez jamaca i bez provjere prihoda",1,"hr","BALKAN","curated","high","financial_fraud"
"Prodajem lijekove na recept povoljno i diskretno",1,"hr","BALKAN","curated","high","illegal_goods"
"Eskort i diskretno društvo u Zagrebu nazovite za info",1,"hr","BALKAN","curated","high","illegal_services"
"Uložite 100 eura i ostvarite 1000 eura zarade za tjedan dana",1,"hr","BALKAN","curated","high","financial_scam"
"Prodajem lažne osobne iskaznice i vozačke dozvole",1,"hr","BALKAN","curated","high","illegal_goods"
"Zaradite lak novac kao dostavljač bez postavljanja pitanja",1,"hr","BALKAN","curated","high","recruitment_scam"
"Tražim mladu djevojku za financijsku suradnju u Splitu",1,"hr","BALKAN","curated","high","transactional_solicitation"
"Kupujem kradenu robu isplata u gotovini odmah na ruke",1,"hr","BALKAN","curated","high","black_market"
"Isplata novca na ruke bez papira javite se na WhatsApp",1,"hr","BALKAN","curated","high","financial_fraud"
"Diskretna masaža i opuštanje u privatnom stanu",1,"hr","BALKAN","curated","high","illegal_services"
"Krediti bez crne liste isplata u roku 15 minuta",1,"hr","BALKAN","curated","high","financial_fraud"
"Kupite ilegalne supstance sigurno i anonimno",1,"hr","BALKAN","curated","high","black_market"
"Sponzoruša traži bogatog muškarca za diskretne susrete",1,"hr","BALKAN","curated","high","transactional_solicitation"
"Legalizacija novca bez porijekla javite se povjerljivo",1,"hr","BALKAN","curated","high","financial_fraud"
"Prodaja oružja bez dozvole brza i tajna dostava",1,"hr","BALKAN","curated","high","black_market"
"Zatražite privatni zajam putem službene banke s niskom kamatom",0,"hr","BALKAN","curated","high","legit_finance"
"Tražim posao stolara imam 5 godina iskustva i preporuke",0,"hr","BALKAN","curated","high","legit_employment"
"Nudimo profesionalno savjetovanje o porezima i financijama",0,"hr","BALKAN","curated","high","legit_business"
"Korišteni kauč na prodaju zbog selidbe preuzimanje u Zagrebu",0,"hr","BALKAN","curated","high","neutral_listing"
"Montažu namještaja pažljivo izvodi ovlašteni majstor",0,"hr","BALKAN","curated","high","legit_services"
"Prodajem automobil uredno servisiran s servisnom knjigom",0,"hr","BALKAN","curated","high","neutral_listing"
"Otvoreno radno mjesto medicinske sestre u bolnici",0,"hr","BALKAN","curated","high","legit_employment"
"Iznajmljuje se namješten stan od sljedećeg mjeseca",0,"hr","BALKAN","curated","high","neutral_listing"
"Instrukcije iz fizike i kemije za osnovnoškolce",0,"hr","BALKAN","curated","high","legit_services"
"Ovlašteni računovođa pomaže oko izrade završnog računa",0,"hr","BALKAN","curated","high","legit_business"
"Profesionalno čišćenje stanova s garancijom kvalitete",0,"hr","BALKAN","curated","high","legit_services"
"Želim kupiti dobar rabljeni gradski bicikl",0,"hr","BALKAN","curated","high","neutral_listing"
"Restoran traži iskusnog kuhara za rad vikendom",0,"hr","BALKAN","curated","high","legit_employment"
"Čuvanje pasa u ugodnom i sigurnom kućnom okruženju",0,"hr","BALKAN","curated","high","legit_services"
"Prodajem rabljeno prijenosno računalo u odličnom stanju",0,"hr","BALKAN","curated","high","neutral_listing"
"Ovlašteni servis vozila vrši dijagnostiku i popravak",0,"hr","BALKAN","curated","high","legit_services"
"Tvrtka iznajmljuje poslovne prostore u sklopu objekta",0,"hr","BALKAN","curated","high","legit_business"
"Tražimo curu za čuvanje djece tri dana u tjednu",0,"hr","BALKAN","curated","high","legit_employment"
"Satovi gitare za početnike i napredne polaznike",0,"hr","BALKAN","curated","high","legit_services"
"Prodajem blagovaonski stol sa šest stolica dobro očuvano",0,"hr","BALKAN","curated","high","neutral_listing"\n""",
        "BG": """"text","label","language","country_group","source","confidence_hint","notes"
"Бързи пари без договор и документи пишете на ЛС",1,"bg","BALKAN","curated","high","financial_fraud"
"Дискретна среща в центъра само в брой DM за инфо",1,"bg","BALKAN","curated","high","illegal_services"
"Работа от вкъщи спечелете 500 евро на ден без опит",1,"bg","BALKAN","curated","high","recruitment_scam"
"Бърз заем без проверка на кредитна история веднага",1,"bg","BALKAN","curated","high","financial_fraud"
"Търся дискретно компания срещу заплащане тази вечер",1,"bg","BALKAN","curated","high","transactional_solicitation"
"Заем без доказване на доходи плащане за минути",1,"bg","BALKAN","curated","high","financial_fraud"
"Продавам лекарства с рецепта евтино и дискретно",1,"bg","BALKAN","curated","high","illegal_goods"
"Ескорт и компания за възрастни в София обадете се",1,"bg","BALKAN","curated","high","illegal_services"
"Инвестирайте 100 лева и вземете 1000 лева след седмица",1,"bg","BALKAN","curated","high","financial_scam"
"Продавам фалшиви шофьорски книжки и лични карти",1,"bg","BALKAN","curated","high","illegal_goods"
"Заработете лесни пари като куриер без въпроси",1,"bg","BALKAN","curated","high","recruitment_scam"
"Търся млада девойка за финансово сътрудничество",1,"bg","BALKAN","curated","high","transactional_solicitation"
"Купувам крадени стоки плащане веднага в брой",1,"bg","BALKAN","curated","high","black_market"
"Бързо изплащане без хартии пишете във WhatsApp",1,"bg","BALKAN","curated","high","financial_fraud"
"Дискретен масаж и релакс в частен апартамент",1,"bg","BALKAN","curated","high","illegal_services"
"Кредити без ЦКР превод до 15 минути",1,"bg","BALKAN","curated","high","financial_fraud"
"Купете незаконни вещества сигурно и анонимно",1,"bg","BALKAN","curated","high","black_market"
"Търся богат мъж за дискретни срещи срещу издръжка",1,"bg","BALKAN","curated","high","transactional_solicitation"
"Легализация на пари без произход пишете ни",1,"bg","BALKAN","curated","high","financial_fraud"
"Продажба на оръжие без разрешително дискретно",1,"bg","BALKAN","curated","high","black_market"
"Заявете личен заем чрез официална банка с ниска лихва",0,"bg","BALKAN","curated","high","legit_finance"
"Търся работа като дърводелец имам 5 години опит",0,"bg","BALKAN","curated","high","legit_employment"
"Предлагаме професионални консултации за данъци и финанси",0,"bg","BALKAN","curated","high","legit_business"
"Употребяван диван се продава поради преместване в София",0,"bg","BALKAN","curated","high","neutral_listing"
"Сглобяване на мебели от квалифициран майстор",0,"bg","BALKAN","curated","high","legit_services"
"Продавам автомобил с пълна сервизна история",0,"bg","BALKAN","curated","high","neutral_listing"
"Свободно място за медицинска сестра в болницата",0,"bg","BALKAN","curated","high","legit_employment"
"Давам обзаведен апартамент под наем от следващия месец",0,"bg","BALKAN","curated","high","neutral_listing"
"Частни уроци по физика и химия за ученици",0,"bg","BALKAN","curated","high","legit_services"
"Счетоводител помага за изготвяне на годишен отчет",0,"bg","BALKAN","curated","high","legit_business"
"Професионално почистване на домове с гаранция",0,"bg","BALKAN","curated","high","legit_services"
"Купувам запазен градски велосипед",0,"bg","BALKAN","curated","high","neutral_listing"
"Ресторант търси опитен готвач за работа през уикенда",0,"bg","BALKAN","curated","high","legit_employment"
"Гледане на кучета в домашна и безопасна среда",0,"bg","BALKAN","curated","high","legit_services"
"Продавам запазен лаптоп в отлично състояние",0,"bg","BALKAN","curated","high","neutral_listing"
"Лицензиран сервиз извършва диагностика и ремонт",0,"bg","BALKAN","curated","high","legit_services"
"Фирма отдава под наем търговски площи в сграда",0,"bg","BALKAN","curated","high","legit_business"
"Търсим жена за гледане на дете три дни в седмицата",0,"bg","BALKAN","curated","high","legit_employment"
"Уроци по китара за начинаещи и напреднали",0,"bg","BALKAN","curated","high","legit_services"
"Продавам трапезна маса с шест стола запазени",0,"bg","BALKAN","curated","high","neutral_listing"\n""",
        "SL": """"text","label","language","country_group","source","confidence_hint","notes"
"Hitri denar brez pogodbe in dokumentov pišite v DM",1,"sl","BALKAN","curated","high","financial_fraud"
"Diskretno srečanje v centru samo gotovina DM za info",1,"sl","BALKAN","curated","high","illegal_services"
"Delo od doma zaslužite 500 evrov na dan brez izkušenj",1,"sl","BALKAN","curated","high","recruitment_scam"
"Hitro posojilo brez preverjanja prihodkov in papirjev",1,"sl","BALKAN","curated","high","financial_fraud"
"Iščem diskretno družbo za plačilo nocoj",1,"sl","BALKAN","curated","high","transactional_solicitation"
"Hitro izplačilo posojila brez zavarovanja na račun",1,"sl","BALKAN","curated","high","financial_fraud"
"Prodam zdravila na recept poceni in diskretno",1,"sl","BALKAN","curated","high","illegal_goods"
"Eskort in diskretna družba v Ljubljani pokličite za info",1,"sl","BALKAN","curated","high","illegal_services"
"Vložite 100 evrov in zaslužite 1000 evrov v enem tednu",1,"sl","BALKAN","curated","high","financial_scam"
"Prodam ponarejena vozniška dovoljenja in dokumente",1,"sl","BALKAN","curated","high","illegal_goods"
"Zaslužite lahek denar kot kurir brez vprašanj",1,"sl","BALKAN","curated","high","recruitment_scam"
"Iščem mlado dekle za finančno sodelovanje v Mariboru",1,"sl","BALKAN","curated","high","transactional_solicitation"
"Kupujem ukradeno blago takojšnje izplačilo v gotovini",1,"sl","BALKAN","curated","high","black_market"
"Takojšnje izplačilo denarja brez papirjev pišite na WhatsApp",1,"sl","BALKAN","curated","high","financial_fraud"
"Diskretna masaža in sprostitev v zasebnem stanovanju",1,"sl","BALKAN","curated","high","illegal_services"
"Posojila brez vpogleda v SISBON izplačilo takoj",1,"sl","BALKAN","curated","high","financial_fraud"
"Kupite prepovedane snovi varno in anonimno",1,"sl","BALKAN","curated","high","black_market"
"Iščem bogatega moškega za diskretna srečanja z nadomestilom",1,"sl","BALKAN","curated","high","transactional_solicitation"
"Legalizacija denarja brez porekla kontaktirajte zaupno",1,"sl","BALKAN","curated","high","financial_fraud"
"Prodaja orožja brez dovoljenja hitra in tajna dostava",1,"sl","BALKAN","curated","high","black_market"
"Zaprosite za osebno posojilo pri uradni banki z nizko obrestno mero",0,"sl","BALKAN","curated","high","legit_finance"
"Iščem delo kot mizar imam 5 let izkušenj in priporočila",0,"sl","BALKAN","curated","high","legit_employment"
"Nudimo strokovno svetovanje o davkih in financah",0,"sl","BALKAN","curated","high","legit_business"
"Rabljen kavč se prodaja zaradi selitve v Ljubljani",0,"sl","BALKAN","curated","high","neutral_listing"
"Montažo pohištva natančno izvede usposobljen mojster",0,"sl","BALKAN","curated","high","legit_services"
"Prodam avtomobil redno servisiran s potrjeno knjižico",0,"sl","BALKAN","curated","high","neutral_listing"
"Prosto delovno mesto za medicinsko sestro v bolnišnici",0,"sl","BALKAN","curated","high","legit_employment"
"Oddaja se opremljeno stanovanje od naslednjega meseca",0,"sl","BALKAN","curated","high","neutral_listing"
"Inštrukcije fizike in kemije za osnovnošolce",0,"sl","BALKAN","curated","high","legit_services"
"Pooblaščeni računovodja pomaga pri izdelavi zaključnega računa",0,"sl","BALKAN","curated","high","legit_business"
"Profesionalno čiščenje stanovanj z garancijo kakovosti",0,"sl","BALKAN","curated","high","legit_services"
"Kupim dobro rabljeno mestno kolo",0,"sl","BALKAN","curated","high","neutral_listing"
"Restavracija išče izkušenega kuharja za delo med vikendi",0,"sl","BALKAN","curated","high","legit_employment"
"Varstvo psov v prijetnem in varnem domačem okolju",0,"sl","BALKAN","curated","high","legit_services"
"Prodam rabljen prenosni računalnik v odličnem stanju",0,"sl","BALKAN","curated","high","neutral_listing"
"Pooblaščeni serviser vozil opravlja diagnostiko in popravila",0,"sl","BALKAN","curated","high","legit_services"
"Podjetje oddaja poslovne prostore v poslovni stavbi",0,"sl","BALKAN","curated","high","legit_business"
"Iščemo varuško za otroka tri dni v tednu",0,"sl","BALKAN","curated","high","legit_employment"
"Ure kitare za začetnike in nadaljevalce",0,"sl","BALKAN","curated","high","legit_services"
"Prodam jedilno mizo s šestimi stolom dobro ohranjeno",0,"sl","BALKAN","curated","high","neutral_listing"\n""",
        "SQ": """"text","label","language","country_group","source","confidence_hint","notes"
"Para të shpejta pa kontratë dhe dokumente shkruani në DM",1,"sq","BALKAN","curated","high","financial_fraud"
"Takim diskret në qendër vetëm para në dorë DM për info",1,"sq","BALKAN","curated","high","illegal_services"
"Puno nga shtëpia fito 500 euro në ditë pa përvojë",1,"sq","BALKAN","curated","high","recruitment_scam"
"Kredi e shpejtë pa verifikim të të ardhurave menjëherë",1,"sq","BALKAN","curated","high","financial_fraud"
"Kërkoj shoqëri diskrete me pagesë sonte",1,"sq","BALKAN","curated","high","transactional_solicitation"
"Hua e shpejtë pa garanci dhe pa letra në llogari",1,"sq","BALKAN","curated","high","financial_fraud"
"Shes barna me recetë lirë dhe në mënyrë konfidenciale",1,"sq","BALKAN","curated","high","illegal_goods"
"Eskortë dhe shoqëri për të rritur në Tiranë telefononi",1,"sq","BALKAN","curated","high","illegal_services"
"Investoni 100 euro dhe fitoni 1000 euro për një javë",1,"sq","BALKAN","curated","high","financial_scam"
"Shes pasaporta dhe leje drejtimi fallco të cilësisë së lartë",1,"sq","BALKAN","curated","high","illegal_goods"
"Fitoni para të lehta si korrier pa bërë pyetje",1,"sq","BALKAN","curated","high","recruitment_scam"
"Kërkoj vajzë të re për bashkëpunim financiar në Durrës",1,"sq","BALKAN","curated","high","transactional_solicitation"
"Blej mallra të vjedhura pagesa menjëherë në dorë",1,"sq","BALKAN","curated","high","black_market"
"Pagesë e shpejtë pa letra na shkruani në WhatsApp",1,"sq","BALKAN","curated","high","financial_fraud"
"Masazh diskret dhe relaks në banesë private",1,"sq","BALKAN","curated","high","illegal_services"
"Kreditë pa verifikim të historisë financiare brenda minutave",1,"sq","BALKAN","curated","high","financial_fraud"
"Bleni substanca të paligjshme në mënyrë të sigurt",1,"sq","BALKAN","curated","high","black_market"
"Kërkoj mashkull të pasur për takime diskrete me pagesë",1,"sq","BALKAN","curated","high","transactional_solicitation"
"Pastrim parash pa origjinë na kontaktoni konfidencialisht",1,"sq","BALKAN","curated","high","financial_fraud"
"Shitje armësh pa leje dërgesë e shpejtë dhe sekret",1,"sq","BALKAN","curated","high","black_market"
"Aplikoni për kredi personale përmes bankës zyrtare me interes të ultë",0,"sq","BALKAN","curated","high","legit_finance"
"Kërkoj punë si marangoz kam 5 vjet përvojë dhe rekomandime",0,"sq","BALKAN","curated","high","legit_employment"
"Ne ofrojmë konsulencë profesionale për taksat dhe financat",0,"sq","BALKAN","curated","high","legit_business"
"Shes divan të përdorur për shkak të lëvizjes në Tiranë",0,"sq","BALKAN","curated","high","neutral_listing"
"Montimi i mobiljeve bëhet nga një mjeshtër i kualifikuar",0,"sq","BALKAN","curated","high","legit_services"
"Shes makinë të përdorur me libër shërbimi të rregullt",0,"sq","BALKAN","curated","high","neutral_listing"
"Vend i lirë pune për infermiere në spitalin rajonal",0,"sq","BALKAN","curated","high","legit_employment"
"Japet me qira banesë e mobiluar nga muaji i ardhshëm",0,"sq","BALKAN","curated","high","neutral_listing"
"Kurse private në fizikë dhe kimi për nxënësit",0,"sq","BALKAN","curated","high","legit_services"
"Kontabilist i autorizuar ndihmon në përgatitjen e bilancit",0,"sq","BALKAN","curated","high","legit_business"
"Pastrim profesional i shtëpive me garanci cilësie",0,"sq","BALKAN","curated","high","legit_services"
"Dua të blej një biçikletë qyteti në gjendje të mirë",0,"sq","BALKAN","curated","high","neutral_listing"
"Restoranti kërkon kuzhinier me përvojë për fundjavë",0,"sq","BALKAN","curated","high","legit_employment"
"Kujdesi për qentë në mjedis shtëpiak dhe të sigurt",0,"sq","BALKAN","curated","high","legit_services"
"Shes laptop të përdorur në gjendje shumë të mirë",0,"sq","BALKAN","curated","high","neutral_listing"
"Servisi i autorizuar i makinave bën diagnostikim dhe riparim",0,"sq","BALKAN","curated","high","legit_services"
"Kompania jep me qira hapësira zyrore në ndërtesë biznesi",0,"sq","BALKAN","curated","high","legit_business"
"Kërkojmë vajzë për kujdesin e fëmijëve tri ditë në javë",0,"sq","BALKAN","curated","high","legit_employment"
"Mësime kitare për fillestarë dhe nivel të avancuar",0,"sq","BALKAN","curated","high","legit_services"
"Shes tryezë ngrënie me gjashtë karrige në gjendje të mirë",0,"sq","BALKAN","curated","high","neutral_listing"\n""",
    }
}

PROCESSED_MAPPING = {
    "v8_sexual": "balkan_v8_base.csv",
    "v8.1_sexual": "balkan_v8_1_slang.csv",
    "v8.2_sexual": "balkan_v8_2_context.csv"
}

def build_balkan_datasets():
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    
    for model_version, country_files in DATASETS.items():
        model_dir = RAW_DIR / model_version / "BALKAN"
        model_dir.mkdir(parents=True, exist_ok=True)
        
        aggregated_dfs = []
        
        for lang_code, csv_content in country_files.items():
            file_path = model_dir / f"{lang_code}.csv"
            
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(csv_content)
            
            df = pd.read_csv(file_path)
            aggregated_dfs.append(df)
            print(f"  └─ Generated RAW: {file_path.relative_to(BASE_DIR)} ({len(df)} rows)")
            
        combined_df = pd.concat(aggregated_dfs, ignore_index=True)
        processed_target = PROCESSED_DIR / PROCESSED_MAPPING[model_version]
        combined_df.to_csv(processed_target, index=False, encoding="utf-8")
        print(f"✅ Aggregated PROCESSED: {processed_target.relative_to(BASE_DIR)} (Total: {len(combined_df)} rows)\n")

if __name__ == "__main__":
    print("🚀 Running Automated BALKAN Dataset Generator (Expanded)...")
    build_balkan_datasets()
    print("🏁 Execution completed successfully.")