from prometheus_client import Counter, Histogram

# 1. Счетчик количества входящих запросов к моделям
MODERATION_REQUESTS_TOTAL = Counter(
    "moderation_requests_total",
    "Total count of moderation requests processed",
    ["version", "verdict"]
)

# 2. Гистограмма распределения выданных скоров (для отслеживания Data Drift в продакшене)
MODERATION_SCORE_DISTRIBUTION = Histogram(
    "moderation_score_distribution",
    "Distribution of prediction scores generated by models",
    ["version"],
    buckets=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
)

# 3. Гистограмма латентности (задержки инференса)
MODERATION_INFERENCE_LATENCY = Histogram(
    "moderation_inference_latency_seconds",
    "Latency of moderation model inference in seconds",
    ["version"]
)